; ======================================================
; RTLDET - non-publishing packet-RAM family probe.
;
; INIT_BASE and RESET must have succeeded and the ISA window must be open.
; DETECT never selects a layout: it restores RTL_CARD_FLAGS on every exit.
; The caller applies policy with RTL.SET_LAYOUT after inspecting A.
; ======================================================

	IFDEF USE_RTL_DETECT

	MODULE RTLDET

DETECT_SRC	EQU RTLDET_BSS_BASE	; 16 bytes: pattern + inverse
DETECT_DST	EQU RTLDET_BSS_BASE + 16	; 16 bytes
DETECT_FLAGS	EQU RTLDET_BSS_BASE + 32
DETECT_HI_ST	EQU RTLDET_BSS_BASE + 33
DETECT_LO_ST	EQU RTLDET_BSS_BASE + 34
DETECT_FIRST	EQU RTLDET_BSS_BASE + 35
DETECT_PAGE	EQU RTLDET_BSS_BASE + 36
DETECT_STAGE	EQU RTLDET_BSS_BASE + 37
DETECT_RESULT	EQU RTLDET_BSS_BASE + 38
; Failure snapshot: stage, page, CR, ISR, CRDA0, CRDA1.
DETECT_SNAPSHOT	EQU RTLDET_BSS_BASE + 39

ENTER_PROBE_MODE
	LD	IX,(RTL_BASE_PTR)
	LD	(IX+RTL_CR_OFF),CR_PAGE0_STOP
	LD	(IX+RTL_DCR_OFF),DCR_INIT
	LD	(IX+RTL_RBCR0_OFF),0
	LD	(IX+RTL_RBCR1_OFF),0
	LD	(IX+RTL_RCR_OFF),RCR_MON
	LD	(IX+RTL_TCR_OFF),TCR_LB_INTERNAL
	LD	(IX+RTL_ISR_OFF),0xFF
	LD	(IX+RTL_IMR_OFF),0
	RET

; Confirm page 0, no active remote DMA and STP. STA is deliberately
; ignored: a DP8390 that has once run may read back STP|STA after STOP.
; ISR.RST is status-only on that part, hence the 7F mask.
CHECK_STOPPED
	LD	IX,(RTL_BASE_PTR)
	LD	A,(IX+RTL_CR_OFF)
	AND	0xD9
	CP	CR_STP
	JR	NZ,.BAD
	LD	A,(IX+RTL_CR_OFF)
	AND	0xD9
	CP	CR_STP
	JR	NZ,.BAD
	LD	A,(IX+RTL_ISR_OFF)
	AND	0x7F
	JR	NZ,.BAD
	LD	A,(IX+RTL_ISR_OFF)
	AND	0x7F
	JR	NZ,.BAD
	OR	A
	RET
.BAD
	SCF
	RET

STOP_AND_CHECK
	LD	IX,(RTL_BASE_PTR)
	LD	(IX+RTL_CR_OFF),CR_PAGE0_STOP
	LD	(IX+RTL_RBCR0_OFF),0
	LD	(IX+RTL_RBCR1_OFF),0
	LD	(IX+RTL_ISR_OFF),0xFF
	JP	CHECK_STOPPED

; Return A = RTL_DET_*. CF is set for DMA_ERROR and CHIP_FAULT.
DETECT
	LD	A,(RTL_CARD_FLAGS)
	LD	(DETECT_FLAGS),A
	LD	A,(RTL_CHIP_KIND)
	CP	RTL_CHIP_REALTEK
	JR	Z,.REALTEK
	LD	A,0x40
	LD	(DETECT_STAGE),A
	CALL	PROBE_PAGE
	JR	C,.DMA_FAIL
	LD	(DETECT_HI_ST),A
	LD	A,0x20
	LD	(DETECT_STAGE),A
	CALL	PROBE_PAGE
	JR	C,.DMA_FAIL
	LD	(DETECT_LO_ST),A

	LD	A,(DETECT_HI_ST)
	CP	RTL_PROBE_UNSTABLE
	JR	Z,.UNKNOWN
	LD	A,(DETECT_LO_ST)
	CP	RTL_PROBE_UNSTABLE
	JR	Z,.UNKNOWN
	LD	A,(DETECT_HI_ST)
	CP	RTL_PROBE_OK
	JR	NZ,.HI_BAD
	LD	A,(DETECT_LO_ST)
	CP	RTL_PROBE_OK
	LD	A,RTL_DET_NE2000
	JR	NZ,.NORMAL_EXIT
	LD	A,RTL_DET_AMBIGUOUS
	JR	.NORMAL_EXIT
.HI_BAD
	LD	A,(DETECT_LO_ST)
	CP	RTL_PROBE_OK
	LD	A,RTL_DET_NE1000
	JR	Z,.NORMAL_EXIT
.UNKNOWN
	LD	A,RTL_DET_UNKNOWN
	JR	.NORMAL_EXIT
.REALTEK
	LD	A,RTL_DET_NE2000
.NORMAL_EXIT
	LD	(DETECT_RESULT),A
	CALL	STOP_AND_CHECK
	JR	C,.CHIP_FAIL
	CALL	RESTORE_FLAGS
	LD	A,(DETECT_RESULT)
	OR	A
	RET

.DMA_FAIL
	; Snapshot before STOP_AND_CHECK writes anything to the controller.
	CALL	SNAPSHOT_FAILURE
	CALL	STOP_AND_CHECK
	JR	C,.CHIP_FAIL
	CALL	RESTORE_FLAGS
	LD	A,RTL_DET_DMA_ERROR
	SCF
	RET
.CHIP_FAIL
	CALL	RESTORE_FLAGS
	LD	A,RTL_DET_CHIP_FAULT
	SCF
	RET

RESTORE_FLAGS
	LD	A,(DETECT_FLAGS)
	LD	(RTL_CARD_FLAGS),A
	RET

SNAPSHOT_FAILURE
	LD	HL,DETECT_SNAPSHOT
	LD	A,(DETECT_STAGE)
	LD	(HL),A
	INC	HL
	LD	A,(DETECT_PAGE)
	LD	(HL),A
	INC	HL
	LD	IX,(RTL_BASE_PTR)
	LD	A,(IX+RTL_CR_OFF)
	LD	(HL),A
	INC	HL
	LD	A,(IX+RTL_ISR_OFF)
	LD	(HL),A
	INC	HL
	LD	A,(IX+RTL_CRDA0_OFF)
	LD	(HL),A
	INC	HL
	LD	A,(IX+RTL_CRDA1_OFF)
	LD	(HL),A
	RET

; Probe a page twice with independent patterns. Each pass writes eight
; bytes at P:0000 and the inverse at P+1:0000, then reads both back.
PROBE_PAGE
	LD	(DETECT_PAGE),A
	LD	HL,DETECT_PAT_A
	CALL	PROBE_ONCE
	JR	C,.TIMEOUT
	LD	(DETECT_FIRST),A
	LD	HL,DETECT_PAT_B
	CALL	PROBE_ONCE
	JR	C,.TIMEOUT
	LD	HL,DETECT_FIRST
	CP	(HL)
	JR	NZ,.UNSTABLE
	OR	A
	RET
.UNSTABLE
	LD	A,RTL_PROBE_UNSTABLE
	OR	A
	RET
.TIMEOUT
	LD	A,RTL_PROBE_TIMEOUT
	SCF
	RET

PROBE_ONCE
	; Materialise pattern and inverse in ordinary RAM.
	LD	DE,DETECT_SRC
	LD	B,8
.COPY
	LD	A,(HL)
	LD	(DE),A
	INC	HL
	INC	DE
	DJNZ	.COPY
	LD	HL,DETECT_SRC
	LD	B,8
.INVERT
	LD	A,(HL)
	CPL
	LD	(DE),A
	INC	HL
	INC	DE
	DJNZ	.INVERT

	LD	A,(DETECT_PAGE)
	LD	D,A
	LD	E,0
	LD	HL,DETECT_SRC
	LD	BC,8
	CALL	@RTL.DMA_WRITE
	RET	C
	LD	A,(DETECT_PAGE)
	INC	A
	LD	D,A
	LD	E,0
	LD	HL,DETECT_SRC+8
	LD	BC,8
	CALL	@RTL.DMA_WRITE
	RET	C
	LD	A,(DETECT_PAGE)
	LD	D,A
	LD	E,0
	LD	HL,DETECT_DST
	LD	BC,8
	CALL	@RTL.DMA_READ
	RET	C
	LD	A,(DETECT_PAGE)
	INC	A
	LD	D,A
	LD	E,0
	LD	HL,DETECT_DST+8
	LD	BC,8
	CALL	@RTL.DMA_READ
	RET	C
	LD	HL,DETECT_SRC
	LD	DE,DETECT_DST
	LD	B,16
.COMPARE
	LD	A,(DE)
	CP	(HL)
	JR	NZ,.MISMATCH
	INC	HL
	INC	DE
	DJNZ	.COMPARE
	LD	A,RTL_PROBE_OK
	OR	A
	RET
.MISMATCH
	LD	A,RTL_PROBE_MISMATCH
	OR	A
	RET

DETECT_PAT_A	DB 0xA5,0x5A,0x3C,0xC3,0x69,0x96,0x81,0x7E
DETECT_PAT_B	DB 0x96,0x69,0xC3,0x3C,0x5A,0xA5,0x7E,0x81

	ENDMODULE
	ENDIF
