; ======================================================
; DLDIRECT - direct-linked counterpart to DLSPEED.
;
; This diagnostic deliberately bypasses libman/UNETRTL while keeping the
; same RTL driver, reliable TCP, HTTP parser, request and RTC measurement.
; Compare it with DLSPEED on the same URL to measure the cost of the public
; DLL path. Developer image only.
; ======================================================

EXE_VERSION	EQU 1
URL_SIZE	EQU 192
HOST_SIZE	EQU 64
PORT_SIZE	EQU 8
PATH_SIZE	EQU 192
REQ_SIZE	EQU 384
HEADER_SIZE	EQU 1024
ALIGN_TIMEOUT	EQU 2500
ARP_TIMEOUT_MS	EQU 3000
SCAN_C		EQU 0xAC

	DEVICE NOSLOT64K

	INCLUDE "macro.inc"
	INCLUDE "dss.inc"
	INCLUDE "memmap.inc"
	INCLUDE "rtl8019.inc"
	INCLUDE "version.inc"

	DEFINE USE_RTL_INIT_NORMAL
	DEFINE USE_RTL_SEND_FRAME
	DEFINE USE_RTL_WAIT_PTX
	DEFINE USE_RTL_RING_HAS_PACKET
	DEFINE USE_RTL_READ_PACKET
	DEFINE USE_ARP_BUILD_REQUEST
	DEFINE USE_ARP_ANSWER
	DEFINE USE_NETENV
	DEFINE USE_RESOLVE
	DEFINE USE_CMDL_PARSE
	DEFINE USE_TCP
	DEFINE USE_TCP_RELIABLE_SEND
	DEFINE USE_TCP_CONTEXT_FULL
	DEFINE USE_UTIL_TPUT
	DEFINE USE_UTIL_PRINT_DEC_32

DHTTP_BSS_BASE	EQU APP_BSS_BASE + 64

	MODULE MAIN

	ORG 0x4100
EXE_HEADER
	DB "EXE"
	DB EXE_VERSION
	DW 0x0100
	DW 0,0,0,0,0
	DW START
	DW START
	DW 0x8000
	DS 234,0

	ORG 0x4200

START
	CLAIM_RUNTIME_PAGE
	LD	(CMDLINE_PTR),IX
	XOR	A
	LD	(CANCELLED),A
	LD	(TCP_IS_OPEN),A
	PRINTLN MSG_BANNER

	CALL	PARSE_CMD_LINE
	JP	C,USAGE_ERROR
	LD	A,(HELP_REQUESTED)
	OR	A
	JP	NZ,SHOW_HELP
	CALL	PARSE_URL
	JP	C,USAGE_ERROR
	CALL	PARSE_PORT
	JP	C,USAGE_ERROR
	CALL	BUILD_HTTP_REQUEST
	PRINT MSG_SOURCE
	PRINTLN URL_BUFF

	LD	HL,N_NET_IP
	LD	DE,OUR_IP
	CALL	@NETENV.REQUIRE_IP
	LD	HL,N_NET_MAC
	LD	DE,OUR_MAC
	CALL	@NETENV.REQUIRE_MAC

	LD	A,1
	LD	(@ISA.ISA_SLOT),A
	CALL	@RTL.INIT_BASE
	JP	C,NO_HARDWARE
	CALL	@RTL.RESET
	JP	C,NETWORK_ERROR
	LD	HL,OUR_MAC
	LD	A,RCR_AB
	CALL	@RTL.INIT_NORMAL
	LD	HL,OUR_MAC
	LD	(@ARP.OUR_MAC_PTR),HL
	LD	HL,OUR_IP
	LD	(@ARP.OUR_IP_PTR),HL

	; Resolve and ARP while the ISA window remains open.
	LD	HL,HOST_BUFF
	LD	DE,TARGET_IP
	CALL	@RESOLVE.HOST
	JP	C,NETWORK_ERROR
	LD	HL,TARGET_IP
	CALL	@RESOLVE.NEXT_HOP_FOR
	JP	C,NETWORK_ERROR
	LD	HL,RESOLVE_NEXT_HOP_MAC
	LD	DE,TARGET_MAC
	LD	BC,6
	LDIR

	LD	HL,TARGET_IP
	LD	DE,TCP_REMOTE_IP
	LD	BC,4
	LDIR
	LD	HL,TARGET_MAC
	LD	DE,TCP_REMOTE_MAC
	LD	BC,6
	LDIR
	LD	A,(PORT_WORD+1)
	LD	(TCP_REMOTE_PORT_HI),A
	LD	A,(PORT_WORD)
	LD	(TCP_REMOTE_PORT_LO),A

	CALL	@ISA.ISA_CLOSE
	PRINT MSG_CONNECTING
	PRINT HOST_BUFF
	LD	A,':'
	CALL	PUT_CHAR
	PRINTLN PORT_BUFF
	CALL	@ISA.ISA_OPEN
	CALL	@TCP.OPEN
	JP	C,TCP_ERROR_OPEN
	LD	A,1
	LD	(TCP_IS_OPEN),A
	CALL	@ISA.ISA_CLOSE

	LD	HL,HEADER_BUFF
	LD	DE,HEADER_SIZE
	CALL	DHTTP.RESET
	PRINTLN MSG_WAIT_EDGE
	CALL	WAIT_RTC_EDGE
	JP	C,RTC_ERROR
	CALL	@UTIL.TPUT_START

	CALL	@ISA.ISA_OPEN
	LD	HL,REQ_BUFF
	CALL	STRLEN
	LD	HL,REQ_BUFF
	CALL	@TCP.SEND
	JP	C,TCP_ERROR_OPEN

	CALL	RECEIVE_BODY
	JP	C,TCP_ERROR_OPEN
	CALL	CLOSE_TCP

	PRINT MSG_RECEIVED
	LD	HL,(DHTTP.BODY_BYTES)
	LD	DE,(DHTTP.BODY_BYTES+2)
	CALL	@UTIL.PRINT_DEC_32
	PRINTLN MSG_BYTES
	LD	HL,(DHTTP.BODY_BYTES)
	LD	DE,(DHTTP.BODY_BYTES+2)
	CALL	REPORT_STOPPED
	JP	C,SAMPLE_TOO_SHORT
	PRINTLN MSG_INTEGRITY_OK
	PRINTLN MSG_RESULT_OK
	LD	B,0
	JP	EXIT

SHOW_HELP
	PRINTLN MSG_USAGE
	LD	B,0
	JP	EXIT
USAGE_ERROR
	PRINTLN MSG_USAGE
	LD	B,1
	JP	FAIL_EXIT
NO_HARDWARE
	CALL	@ISA.ISA_CLOSE
	PRINTLN MSG_NO_HARDWARE
	LD	B,2
	JP	FAIL_EXIT
RTC_ERROR
	CALL	CLOSE_TCP
	PRINTLN MSG_RTC_ERROR
	LD	B,3
	JP	FAIL_EXIT
SAMPLE_TOO_SHORT
	PRINTLN MSG_SAMPLE_SHORT
	LD	B,3
	JP	FAIL_EXIT
TCP_ERROR_OPEN
	LD	(API_STATUS),A
	CALL	@ISA.ISA_CLOSE
	CALL	CLOSE_TCP
	PRINT MSG_TCP_ERROR
	LD	A,(TCP_LAST_FAIL)
	CALL	@UTIL.PRINT_HEX_A
	CALL	CRLF
	LD	B,3
	JP	FAIL_EXIT
NETWORK_ERROR
	CALL	@ISA.ISA_CLOSE
	PRINTLN MSG_NETWORK_ERROR
	LD	B,3
FAIL_EXIT
	PUSH	BC
	PRINTLN MSG_RESULT_FAIL
	POP	BC
EXIT
	LD	C,DSS_EXIT
	RST	DSS

CLOSE_TCP
	LD	A,(TCP_IS_OPEN)
	OR	A
	RET	Z
	CALL	@ISA.ISA_OPEN
	CALL	@TCP.CLOSE
	CALL	@ISA.ISA_CLOSE
	XOR	A
	LD	(TCP_IS_OPEN),A
	RET

; Direct TCP.RECV publishes one segment in TCP_RX_DATA_PTR/LEN. The parser
; discards it immediately. ISA remains open until the exact body boundary.
RECEIVE_BODY
.LOOP
	CALL	@TCP.RECV
	JR	NC,.HAVE
	LD	A,(TCP_STATE)
	CP	@TCP.ST_CLOSE_WAIT
	JR	NZ,.FAILED
	LD	BC,(TCP_RX_DATA_LEN)
	LD	A,B
	OR	C
	JR	Z,.FAILED
	JR	.PROCESS
.HAVE
	LD	BC,(TCP_RX_DATA_LEN)
.PROCESS
	LD	HL,(TCP_RX_DATA_PTR)
	IFDEF DLDIRECT_COPY
	PUSH	BC
	LD	DE,DIRECT_COPY_BUF
	LDIR
	POP	BC
	LD	HL,DIRECT_COPY_BUF
	ENDIF
	CALL	DHTTP.CONSUME
	JR	C,.FAILED
	OR	A
	JR	NZ,.DONE
	LD	A,(TCP_STATE)
	CP	@TCP.ST_CLOSE_WAIT
	JR	Z,.FAILED
	JR	.LOOP
.DONE
	CALL	@ISA.ISA_CLOSE
	CALL	CAPTURE_STOP
	XOR	A
	RET
.FAILED
	SCF
	RET

WAIT_RTC_EDGE
	CALL	@UTIL.TPUT_NOW
	LD	(ALIGN_SECOND),HL
	LD	A,B
	LD	(ALIGN_SECOND+2),A
	LD	HL,ALIGN_TIMEOUT
	LD	(ALIGN_LEFT),HL
.LOOP
	CALL	@UTIL.DELAY_1MS
	CALL	@UTIL.TPUT_NOW
	LD	DE,(ALIGN_SECOND)
	OR	A
	SBC	HL,DE
	JR	NZ,.EDGE
	LD	A,(ALIGN_SECOND+2)
	CP	B
	JR	NZ,.EDGE
	LD	HL,(ALIGN_LEFT)
	DEC	HL
	LD	(ALIGN_LEFT),HL
	LD	A,H
	OR	L
	JR	NZ,.LOOP
	SCF
	RET
.EDGE
	OR	A
	RET

CAPTURE_STOP
	CALL	@UTIL.TPUT_NOW
	LD	(STOP_TIME),HL
	LD	A,B
	LD	(STOP_TIME+2),A
	RET

; Same saved-stop report as DLSPEED.
REPORT_STOPPED
	LD	(UTIL_HBUF),HL
	LD	(UTIL_HBUF+2),DE
	LD	HL,(STOP_TIME)
	LD	A,(STOP_TIME+2)
	LD	B,A
	LD	DE,(UTIL_TPUT_START)
	LD	A,L
	SUB	E
	LD	L,A
	LD	A,H
	SBC	A,D
	LD	H,A
	LD	A,(UTIL_TPUT_START+2)
	LD	E,A
	LD	A,B
	SBC	A,E
	LD	B,A
	JR	NC,.NO_WRAP
	LD	DE,0x5180
	ADD	HL,DE
	LD	A,B
	ADC	A,1
	LD	B,A
.NO_WRAP
	LD	(STOP_ELAPSED),HL
	LD	A,B
	LD	(STOP_ELAPSED+2),A
	OR	H
	OR	L
	JP	Z,.TOO_SHORT
	PRINT MSG_RATE_PREFIX
	LD	HL,(UTIL_HBUF)
	LD	DE,(UTIL_HBUF+2)
	CALL	@UTIL.PRINT_DEC_32
	PRINT MSG_RATE_BYTES
	LD	HL,(STOP_ELAPSED)
	LD	A,(STOP_ELAPSED+2)
	LD	E,A
	LD	D,0
	CALL	@UTIL.PRINT_DEC_32
	PRINT MSG_RATE_SEC
	LD	A,(STOP_ELAPSED+2)
	OR	A
	JR	NZ,.DONE
	LD	HL,(UTIL_HBUF)
	LD	(UTIL_DEC32_SCRATCH),HL
	LD	HL,(UTIL_HBUF+2)
	LD	(UTIL_DEC32_SCRATCH+2),HL
	LD	DE,(STOP_ELAPSED)
	CALL	@UTIL.DIV32_BY_DE
	PRINT MSG_RATE_COMMA
	LD	A,(UTIL_DEC32_SCRATCH+3)
	OR	A
	JR	NZ,.KIB
	LD	A,(UTIL_DEC32_SCRATCH+2)
	OR	A
	JR	NZ,.KIB
	LD	A,(UTIL_DEC32_SCRATCH+1)
	CP	4
	JR	NC,.KIB
	LD	HL,(UTIL_DEC32_SCRATCH)
	LD	DE,(UTIL_DEC32_SCRATCH+2)
	CALL	@UTIL.PRINT_DEC_32
	PRINT MSG_RATE_BPS
	JR	.DONE
.KIB
	LD	HL,(UTIL_DEC32_SCRATCH)
	LD	DE,(UTIL_DEC32_SCRATCH+2)
	LD	L,H
	LD	H,E
	LD	E,D
	LD	D,0
	SRL	E
	RR	H
	RR	L
	SRL	E
	RR	H
	RR	L
	CALL	@UTIL.PRINT_DEC_32
	PRINT MSG_RATE_KIB
.DONE
	CALL	CRLF
	OR	A
	RET
.TOO_SHORT
	SCF
	RET

; Resolver callback, identical to the direct clients.
WAIT_FOR_ARP_REPLY
.LOOP
	CALL	@RTL.RING_HAS_PACKET
	JR	NZ,.HAVE
.TICK
	CALL	TICK_AND_CHECK_KEY
	JR	C,.TIMEOUT
	LD	HL,(TIMEOUT_MS_LEFT)
	DEC	HL
	LD	(TIMEOUT_MS_LEFT),HL
	LD	A,H
	OR	L
	JR	NZ,.LOOP
	JR	.TIMEOUT
.HAVE
	LD	HL,RX_HDR
	LD	DE,RX_BUF
	LD	BC,RX_BUF_SIZE
	CALL	@RTL.READ_PACKET
	JR	C,.TICK
	LD	A,(RX_BUF+12)
	CP	0x08
	JR	NZ,.TICK
	LD	A,(RX_BUF+13)
	CP	0x06
	JR	NZ,.TICK
	LD	A,(RX_BUF+20)
	OR	A
	JR	NZ,.TICK
	LD	A,(RX_BUF+21)
	CP	2
	JR	NZ,.TICK
	LD	HL,RX_BUF+28
	LD	DE,TARGET_IP
	LD	B,4
.CMP
	LD	A,(DE)
	CP	(HL)
	JR	NZ,.TICK
	INC	HL
	INC	DE
	DJNZ	.CMP
	LD	HL,RX_BUF+22
	LD	DE,TARGET_MAC
	LD	BC,6
	LDIR
	OR	A
	RET
.TIMEOUT
	SCF
	RET

TICK_AND_CHECK_KEY
	CALL	@ISA.ISA_CLOSE
	CALL	@UTIL.DELAY_1MS
	LD	C,DSS_SCANKEY
	RST	DSS
	JR	Z,.NO_KEY
	LD	A,E
	CP	0x1B
	JR	Z,.CANCEL
	LD	A,B
	AND	KB_CTRL | KB_L_CTRL | KB_R_CTRL
	JR	Z,.NO_KEY
	LD	A,D
	CP	SCAN_C
	JR	Z,.CANCEL
.NO_KEY
	CALL	@ISA.ISA_OPEN
	OR	A
	RET
.CANCEL
	LD	A,1
	LD	(CANCELLED),A
	CALL	@ISA.ISA_OPEN
	SCF
	RET

; Command line and URL/request helpers mirror DLSPEED.
PARSE_CMD_LINE
	XOR	A
	LD	(HELP_REQUESTED),A
	LD	HL,(CMDLINE_PTR)
	LD	A,(HL)
	OR	A
	JR	Z,.ERR
	LD	B,A
	INC	HL
	CALL	SKIP_SPACES
	JR	C,.ERR
	LD	DE,URL_BUFF
	LD	C,URL_SIZE-1
	CALL	COPY_ARG
	JR	C,.ERR
	LD	HL,URL_BUFF
	LD	DE,SWITCH_HELP
	CALL	STREQ
	JR	NZ,.NOT_HELP
	LD	A,1
	LD	(HELP_REQUESTED),A
.NOT_HELP
	CALL	ONLY_SPACES_LEFT
	RET	NC
.ERR
	SCF
	RET
SKIP_SPACES
	LD	A,B
	OR	A
	JR	Z,.ERR
	LD	A,(HL)
	CP	0x21
	RET	NC
	INC	HL
	DJNZ	SKIP_SPACES
.ERR
	SCF
	RET
COPY_ARG
	LD	A,B
	OR	A
	JR	Z,.DONE
	LD	A,(HL)
	CP	0x21
	JR	C,.DONE
	LD	A,C
	OR	A
	JR	Z,.ERR
	LD	A,(HL)
	LD	(DE),A
	INC	HL
	INC	DE
	DEC	B
	DEC	C
	JR	COPY_ARG
.DONE
	XOR	A
	LD	(DE),A
	RET
.ERR
	SCF
	RET
ONLY_SPACES_LEFT
	LD	A,B
	OR	A
	RET	Z
	LD	A,(HL)
	CP	0x21
	JR	NC,.ERR
	INC	HL
	DJNZ	ONLY_SPACES_LEFT
	OR	A
	RET
.ERR
	SCF
	RET

PARSE_URL
	LD	HL,URL_BUFF
	LD	DE,HTTP_SCHEME
	CALL	STARTSWITH
	JP	NZ,.ERR
	LD	BC,7
	ADD	HL,BC
	LD	DE,HOST_BUFF
	LD	C,HOST_SIZE-1
.HOST
	LD	A,(HL)
	OR	A
	JR	Z,.HOST_DONE
	CP	'/'
	JR	Z,.HOST_DONE
	CP	':'
	JR	Z,.PORT_START
	LD	A,C
	OR	A
	JR	Z,.ERR
	LD	A,(HL)
	LD	(DE),A
	INC	HL
	INC	DE
	DEC	C
	JR	.HOST
.HOST_DONE
	XOR	A
	LD	(DE),A
	LD	A,(HOST_BUFF)
	OR	A
	JR	Z,.ERR
	PUSH	HL
	LD	HL,DEFAULT_PORT
	LD	DE,PORT_BUFF
	CALL	COPY_ASCIIZ
	POP	HL
	JR	.PATH_START
.PORT_START
	XOR	A
	LD	(DE),A
	INC	HL
	LD	DE,PORT_BUFF
	LD	C,PORT_SIZE-1
.PORT
	LD	A,(HL)
	OR	A
	JR	Z,.PORT_DONE
	CP	'/'
	JR	Z,.PORT_DONE
	CP	'0'
	JR	C,.ERR
	CP	'9'+1
	JR	NC,.ERR
	LD	A,C
	OR	A
	JR	Z,.ERR
	LD	A,(HL)
	LD	(DE),A
	INC	HL
	INC	DE
	DEC	C
	JR	.PORT
.PORT_DONE
	XOR	A
	LD	(DE),A
	LD	A,(PORT_BUFF)
	OR	A
	JR	Z,.ERR
.PATH_START
	LD	A,(HL)
	CP	'/'
	JR	Z,.COPY_PATH
	OR	A
	JR	NZ,.ERR
	LD	HL,DEFAULT_PATH
.COPY_PATH
	LD	DE,PATH_BUFF
	LD	C,PATH_SIZE-1
.PATH
	LD	A,(HL)
	OR	A
	JR	Z,.PATH_DONE
	LD	A,C
	OR	A
	JR	Z,.ERR
	LD	A,(HL)
	LD	(DE),A
	INC	HL
	INC	DE
	DEC	C
	JR	.PATH
.PATH_DONE
	XOR	A
	LD	(DE),A
	OR	A
	RET
.ERR
	SCF
	RET

PARSE_PORT
	LD	HL,PORT_BUFF
	LD	DE,0
.LOOP
	LD	A,(HL)
	OR	A
	JR	Z,.DONE
	SUB	'0'
	JR	C,.ERR
	CP	10
	JR	NC,.ERR
	LD	B,A
	PUSH	HL
	LD	H,D
	LD	L,E
	ADD	HL,HL
	LD	D,H
	LD	E,L
	ADD	HL,HL
	ADD	HL,HL
	ADD	HL,DE
	LD	D,0
	LD	E,B
	ADD	HL,DE
	EX	DE,HL
	POP	HL
	INC	HL
	JR	.LOOP
.DONE
	LD	(PORT_WORD),DE
	LD	A,D
	OR	E
	JR	Z,.ERR
	OR	A
	RET
.ERR
	SCF
	RET

BUILD_HTTP_REQUEST
	LD	HL,REQ_BUFF
	LD	DE,REQ_GET
	CALL	APPEND_STR
	LD	DE,PATH_BUFF
	CALL	APPEND_STR
	LD	DE,REQ_HOST
	CALL	APPEND_STR
	LD	DE,HOST_BUFF
	CALL	APPEND_STR
	PUSH	HL
	LD	HL,PORT_BUFF
	LD	DE,DEFAULT_PORT
	CALL	STREQ
	POP	HL
	JR	Z,.DEFAULT
	LD	DE,REQ_COLON
	CALL	APPEND_STR
	LD	DE,PORT_BUFF
	CALL	APPEND_STR
.DEFAULT
	LD	DE,REQ_END
	JP	APPEND_STR
APPEND_STR
	LD	A,(DE)
	LD	(HL),A
	OR	A
	RET	Z
	INC	HL
	INC	DE
	JR	APPEND_STR
COPY_ASCIIZ
	LD	A,(HL)
	LD	(DE),A
	OR	A
	RET	Z
	INC	HL
	INC	DE
	JR	COPY_ASCIIZ
STARTSWITH
	PUSH	HL
.LOOP
	LD	A,(DE)
	OR	A
	JR	Z,.MATCH
	CP	(HL)
	JR	NZ,.MISS
	INC	HL
	INC	DE
	JR	.LOOP
.MATCH
	POP	HL
	XOR	A
	RET
.MISS
	POP	HL
	LD	A,0xFF
	OR	A
	RET
STREQ
	LD	A,(DE)
	LD	C,A
	LD	A,(HL)
	CP	C
	RET	NZ
	AND	A
	RET	Z
	INC	HL
	INC	DE
	JR	STREQ
STRLEN
	LD	BC,0
.LOOP
	LD	A,(HL)
	OR	A
	RET	Z
	INC	HL
	INC	BC
	JR	.LOOP

PUT_CHAR
	PUSH	AF,BC,DE,HL
	LD	C,DSS_PUTCHAR
	RST	DSS
	POP	HL,DE,BC,AF
	RET
CRLF
	PRINT LINE_END
	RET

	IFDEF DLDIRECT_COPY
MSG_BANNER	DB "DLDIRCP v",PACKAGE_VERSION," - direct RTL plus copy",0
	ELSE
MSG_BANNER	DB "DLDIRECT v",PACKAGE_VERSION," - direct RTL throughput",0
	ENDIF
MSG_USAGE	DB "Usage: DLDIRECT.EXE http://host[:port]/path",13,10
		DB "       DLDIRECT.EXE /?",13,10
		DB "Compare with DLSPEED using the same 4 MiB URL.",0
MSG_SOURCE	DB "Source: ",0
MSG_CONNECTING	DB "Connecting to ",0
MSG_WAIT_EDGE	DB "Waiting for RTC edge; transfer is silent until done...",0
MSG_RECEIVED	DB "Received: ",0
MSG_BYTES	DB " bytes",0
MSG_RATE_PREFIX	DB "  ",0
MSG_RATE_BYTES	DB " bytes in ",0
MSG_RATE_SEC	DB " sec",0
MSG_RATE_COMMA	DB ", ",0
MSG_RATE_BPS	DB " B/s",0
MSG_RATE_KIB	DB " KB/s",0
MSG_INTEGRITY_OK DB "Integrity: OK",0
MSG_SAMPLE_SHORT DB "Sample too short (less than one RTC second).",0
MSG_RTC_ERROR	DB "RTC second did not advance.",0
MSG_NO_HARDWARE	DB "RTL8019AS not detected.",0
MSG_NETWORK_ERROR DB "Network setup/resolve error.",0
MSG_TCP_ERROR	DB "TCP/HTTP error #",0
MSG_RESULT_OK	DB "RESULT OK",0
MSG_RESULT_FAIL	DB "RESULT FAIL",0
LINE_END	DB 13,10,0
N_NET_IP	DB "NET_IP",0
N_NET_MAC	DB "NET_MAC",0
HTTP_SCHEME	DB "http://",0
DEFAULT_PORT	DB "80",0
DEFAULT_PATH	DB "/",0
SWITCH_HELP	DB "/?",0
REQ_GET		DB "GET ",0
REQ_HOST	DB " HTTP/1.1",13,10,"Host: ",0
REQ_COLON	DB ":",0
REQ_END		DB 13,10,"Accept-Encoding: identity",13,10
		DB "Connection: keep-alive",13,10,13,10,0

	ENDMODULE

	INCLUDE "win2page.asm"
	INCLUDE "netenv_lib.asm"
	INCLUDE "cmdline_lib.asm"
	INCLUDE "isa.asm"
	INCLUDE "util.asm"
	INCLUDE "rtl8019.asm"
	INCLUDE "arp_lib.asm"
	INCLUDE "resolve_lib.asm"
	INCLUDE "dns_lib.asm"
	INCLUDE "tcp_lib.asm"
	INCLUDE "dlspeed_http.asm"

DLDIRECT_IMAGE_END
RX_BUF_SIZE	EQU 1518

	MODULE MAIN

OUR_IP		EQU APP_BSS_BASE
OUR_MAC		EQU APP_BSS_BASE + 4
TARGET_IP	EQU APP_BSS_BASE + 10
TARGET_MAC	EQU APP_BSS_BASE + 14
TIMEOUT_MS_LEFT EQU APP_BSS_BASE + 20
PORT_WORD	EQU APP_BSS_BASE + 22
CANCELLED	EQU APP_BSS_BASE + 24
TCP_IS_OPEN	EQU APP_BSS_BASE + 25
CMDLINE_PTR	EQU APP_BSS_BASE + 26
HELP_REQUESTED	EQU APP_BSS_BASE + 28
API_STATUS	EQU APP_BSS_BASE + 29
ALIGN_SECOND	EQU APP_BSS_BASE + 30
ALIGN_LEFT	EQU APP_BSS_BASE + 33
STOP_TIME	EQU APP_BSS_BASE + 35
STOP_ELAPSED	EQU APP_BSS_BASE + 38

URL_BUFF	EQU DHTTP_BSS_BASE + DHTTP_BSS_SIZE
HOST_BUFF	EQU URL_BUFF + URL_SIZE
PORT_BUFF	EQU HOST_BUFF + HOST_SIZE
PATH_BUFF	EQU PORT_BUFF + PORT_SIZE
REQ_BUFF	EQU PATH_BUFF + PATH_SIZE
HEADER_BUFF	EQU REQ_BUFF + REQ_SIZE
	IFDEF DLDIRECT_COPY
DIRECT_COPY_BUF EQU HEADER_BUFF + HEADER_SIZE
APP_BSS_END	EQU DIRECT_COPY_BUF + 536
	ELSE
APP_BSS_END	EQU HEADER_BUFF + HEADER_SIZE
	ENDIF

TX_BUF		EQU DLDIRECT_IMAGE_END
RX_HDR		EQU TX_BUF + TCP_MAX_FRAME
RX_BUF		EQU RX_HDR + 4

	ASSERT RX_BUF + RX_BUF_SIZE < 0x8000
	ASSERT APP_BSS_END < RT_STACK_TOP - 0x0100
	ENDMODULE

	END MAIN.START
