; ======================================================
; DLSPEED - backend-neutral UNET HTTP download throughput test.
;
;   DLSPEED http://host[:port]/path
;   DLSPEED /?
;
; The application owns window 2 and loads UNETRTL.DLL into window 1. It
; discards the HTTP body while counting an exact Content-Length, so transfer
; size is not limited by the receive buffer. No progress is printed while the
; RTC-aligned measurement is running.
; ======================================================

EXE_VERSION	EQU 1
URL_SIZE	EQU 192
HOST_SIZE	EQU 64
PORT_SIZE	EQU 8
PATH_SIZE	EQU 192
REQ_SIZE	EQU 384
HEADER_SIZE	EQU 512
; Deliberately exceed the DLL's three-MSS cumulative-ACK group by one MSS.
; This exercises the intermediate ACK while retaining one public RECV call.
RECV_SIZE	EQU 2144
RECV_TIMEOUT	EQU 7000
ALIGN_TIMEOUT	EQU 2500

	DEVICE NOSLOT64K

	INCLUDE "dss.inc"
	INCLUDE "unet.inc"
	INCLUDE "version.inc"
	INCLUDE "memmap.inc"

	MODULE MAIN

	ORG 0x8080
EXE_HEADER
	DB "EXE"
	DB EXE_VERSION
	DW 0x0080
	DW 0,0,0,0,0
	DW START
	DW START
	DW STACK_TOP
	DS 106,0

	ORG 0x8100

START
	LD	(CMDLINE_PTR),IX
	LD	SP,STACK_TOP
	XOR	A
	LD	(DLL_LOADED),A
	LD	(NET_INITED),A
	LD	(TCP_OPEN),A

	LD	HL,MSG_BANNER
	CALL	PUTS_LN
	CALL	PARSE_CMD_LINE
	JP	C,USAGE_ERROR
	LD	A,(HELP_REQUESTED)
	OR	A
	JP	NZ,SHOW_HELP
	CALL	PARSE_URL
	JP	C,USAGE_ERROR
	CALL	BUILD_HTTP_REQUEST

	LD	HL,MSG_SOURCE
	CALL	PUTS
	LD	HL,URL_BUFF
	CALL	PUTS_LN
	LD	HL,MSG_LOADING
	CALL	PUTS
	LD	HL,DLL_NAME
	CALL	PUTS_LN
	LD	HL,DLL_NAME
	LD	A,1
	CALL	LIBMAN.l_load
	JP	C,LOAD_ERROR
	LD	(HANDLE),HL
	LD	A,1
	LD	(DLL_LOADED),A

	LD	B,UNET_FN_GETCAPS
	CALL	DO_CALL
	OR	A
	JP	NZ,API_ERROR
	PUSH	IX
	POP	HL
	LD	A,H
	CP	HIGH UNET_ABI_VERSION
	JP	NZ,ABI_ERROR
	LD	A,E
	AND	UNET_CAP_TCP
	JP	Z,ABI_ERROR

	LD	A,UNET_OPT_CANCELKEYS
	LD	DE,1
	LD	B,UNET_FN_SETOPT
	CALL	DO_CALL
	OR	A
	JP	NZ,API_ERROR

	LD	B,UNET_FN_NETINIT
	CALL	DO_CALL
	OR	A
	JP	NZ,API_ERROR
	LD	A,1
	LD	(NET_INITED),A

	LD	HL,MSG_CONNECTING
	CALL	PUTS
	LD	HL,HOST_BUFF
	CALL	PUTS
	LD	A,':'
	CALL	PUT_CHAR
	LD	HL,PORT_BUFF
	CALL	PUTS_LN
	XOR	A
	LD	DE,HOST_BUFF
	LD	IX,PORT_BUFF
	LD	B,UNET_FN_CONNECT
	CALL	DO_CALL
	OR	A
	JP	NZ,API_ERROR
	LD	A,1
	LD	(TCP_OPEN),A

	LD	HL,HEADER_BUFF
	LD	DE,HEADER_SIZE
	CALL	DHTTP.RESET
	LD	HL,MSG_WAIT_EDGE
	CALL	PUTS_LN
	CALL	WAIT_RTC_EDGE
	JP	C,RTC_ERROR
	CALL	@UTIL.TPUT_START

	LD	HL,REQ_BUFF
	CALL	STRLEN
	PUSH	BC
	POP	IX
	LD	DE,REQ_BUFF
	XOR	A
	LD	B,UNET_FN_SEND
	CALL	DO_CALL
	OR	A
	JP	NZ,API_ERROR

	CALL	RECEIVE_BODY
	JP	C,RECEIVE_ERROR

	CALL	CLEANUP
	LD	HL,MSG_RECEIVED
	CALL	PUTS
	LD	HL,(DHTTP.BODY_BYTES)
	LD	DE,(DHTTP.BODY_BYTES+2)
	CALL	@UTIL.PRINT_DEC_32
	LD	HL,MSG_BYTES
	CALL	PUTS_LN
	LD	HL,(DHTTP.BODY_BYTES)
	LD	DE,(DHTTP.BODY_BYTES+2)
	CALL	REPORT_STOPPED
	JP	C,SAMPLE_TOO_SHORT
	LD	HL,MSG_INTEGRITY_OK
	CALL	PUTS_LN
	LD	HL,MSG_RESULT_OK
	CALL	PUTS_LN
	LD	B,0
	JP	EXIT

SHOW_HELP
	LD	HL,MSG_USAGE
	CALL	PUTS_LN
	LD	B,0
	JP	EXIT

USAGE_ERROR
	LD	HL,MSG_USAGE
	CALL	PUTS_LN
	LD	B,1
	JP	FAIL_EXIT

LOAD_ERROR
	LD	HL,MSG_LOAD_ERROR
	CALL	PUTS_LN
	LD	B,2
	JP	FAIL_EXIT

ABI_ERROR
	LD	HL,MSG_ABI_ERROR
	CALL	PUTS_LN
	CALL	CLEANUP
	LD	B,3
	JP	FAIL_EXIT

RTC_ERROR
	LD	HL,MSG_RTC_ERROR
	CALL	PUTS_LN
	CALL	CLEANUP
	LD	B,3
	JP	FAIL_EXIT

SAMPLE_TOO_SHORT
	LD	HL,MSG_SAMPLE_SHORT
	CALL	PUTS_LN
	LD	B,3
	JP	FAIL_EXIT

API_ERROR
	LD	(API_STATUS),A
	CALL	DUMP_LASTERR
	CALL	CLEANUP
	LD	HL,MSG_NET_ERROR
	CALL	PUTS
	LD	A,(API_STATUS)
	CALL	PRINT_DEC_A
	CALL	CRLF
	LD	A,(API_STATUS)
	CP	NERR_HW
	LD	B,2
	JR	Z,FAIL_EXIT
	CP	NERR_NONET
	LD	B,4
	JR	Z,FAIL_EXIT
	LD	B,3
	JR	FAIL_EXIT

RECEIVE_ERROR
	LD	(API_STATUS),A
	LD	A,(DHTTP.ERROR)
	OR	A
	JR	NZ,.HTTP
	LD	A,(API_STATUS)
	CP	NERR_CANCEL
	LD	HL,MSG_CANCELLED
	JR	Z,.SAY
	CP	NERR_CLOSED
	LD	HL,MSG_INCOMPLETE
	JR	Z,.SAY
	CALL	DUMP_LASTERR
	LD	HL,MSG_RECV_ERROR
	JR	.SAY
.HTTP
	LD	HL,MSG_HTTP_ERROR
.SAY
	CALL	PUTS
	LD	A,(API_STATUS)
	CALL	PRINT_DEC_A
	CALL	CRLF
	CALL	CLEANUP
	LD	B,3
	JR	FAIL_EXIT

FAIL_EXIT
	PUSH	BC
	LD	HL,MSG_RESULT_FAIL
	CALL	PUTS_LN
	POP	BC
EXIT
	LD	C,DSS_EXIT
	RST	DSS

; Receive data until the parser reaches the exact Content-Length boundary.
RECEIVE_BODY
.LOOP
	XOR	A
	LD	DE,RECV_BUFF
	LD	IX,RECV_SIZE
	LD	IY,RECV_TIMEOUT
	LD	B,UNET_FN_RECV
	CALL	DO_CALL
	LD	(API_STATUS),A
	LD	A,D
	OR	E
	JR	Z,.NO_DATA
	PUSH	DE
	POP	BC
	LD	HL,RECV_BUFF
	CALL	DHTTP.CONSUME
	JR	C,.HTTP_ERROR
	OR	A
	JR	NZ,.DONE
	LD	A,(API_STATUS)
	CP	NERR_CLOSED
	JR	Z,.FAILED
	OR	A
	JR	Z,.LOOP
	JR	.FAILED
.NO_DATA
	LD	A,(API_STATUS)
	OR	A
	JR	Z,.LOOP
.FAILED
	SCF
	RET
.HTTP_ERROR
	SCF
	RET
.DONE
	CALL	CAPTURE_STOP
	XOR	A
	RET

; Wait for the RTC second to advance, bounded so a stopped RTC cannot hang.
WAIT_RTC_EDGE
	CALL	@UTIL.TPUT_NOW
	LD	(ALIGN_SECOND),HL
	LD	A,B
	LD	(ALIGN_SECOND+2),A
	LD	HL,ALIGN_TIMEOUT
	LD	(ALIGN_LEFT),HL
.LOOP
	CALL	@UTIL.DELAY_1MS
	CALL	@UTIL.TPUT_NOW
	LD	DE,(ALIGN_SECOND)
	OR	A
	SBC	HL,DE
	JR	NZ,.EDGE
	LD	A,(ALIGN_SECOND+2)
	CP	B
	JR	NZ,.EDGE
	LD	HL,(ALIGN_LEFT)
	DEC	HL
	LD	(ALIGN_LEFT),HL
	LD	A,H
	OR	L
	JR	NZ,.LOOP
	SCF
	RET
.EDGE
	OR	A
	RET

; Capture the measurement boundary before CLOSE/NETDONE or console output.
CAPTURE_STOP
	CALL	@UTIL.TPUT_NOW
	LD	(STOP_TIME),HL
	LD	A,B
	LD	(STOP_TIME+2),A
	RET

; Report using the saved stop time. This routine never reads the RTC.
; In: DE:HL = bytes. Out: CF=1 for a zero-second sample.
REPORT_STOPPED
	LD	(UTIL_HBUF),HL
	LD	(UTIL_HBUF+2),DE
	LD	HL,(STOP_TIME)
	LD	A,(STOP_TIME+2)
	LD	B,A
	LD	DE,(UTIL_TPUT_START)
	LD	A,L
	SUB	E
	LD	L,A
	LD	A,H
	SBC	A,D
	LD	H,A
	LD	A,(UTIL_TPUT_START+2)
	LD	E,A
	LD	A,B
	SBC	A,E
	LD	B,A
	JR	NC,.NO_WRAP
	LD	DE,0x5180		; add 86400 after midnight
	ADD	HL,DE
	LD	A,B
	ADC	A,1
	LD	B,A
.NO_WRAP
	LD	(STOP_ELAPSED),HL
	LD	A,B
	LD	(STOP_ELAPSED+2),A
	OR	H
	OR	L
	JP	Z,.TOO_SHORT

	LD	HL,MSG_RATE_PREFIX
	CALL	PUTS
	LD	HL,(UTIL_HBUF)
	LD	DE,(UTIL_HBUF+2)
	CALL	@UTIL.PRINT_DEC_32
	LD	HL,MSG_RATE_BYTES
	CALL	PUTS
	LD	HL,(STOP_ELAPSED)
	LD	A,(STOP_ELAPSED+2)
	LD	E,A
	LD	D,0
	CALL	@UTIL.PRINT_DEC_32
	LD	HL,MSG_RATE_SEC
	CALL	PUTS

	; The normal test is seconds or minutes. For an implausible duration over
	; 18 hours, print elapsed time but omit a rate that needs a 24-bit divisor.
	LD	A,(STOP_ELAPSED+2)
	OR	A
	JR	NZ,.DONE
	LD	HL,(UTIL_HBUF)
	LD	(UTIL_DEC32_SCRATCH),HL
	LD	HL,(UTIL_HBUF+2)
	LD	(UTIL_DEC32_SCRATCH+2),HL
	LD	DE,(STOP_ELAPSED)
	CALL	@UTIL.DIV32_BY_DE
	LD	HL,MSG_RATE_COMMA
	CALL	PUTS
	LD	A,(UTIL_DEC32_SCRATCH+3)
	OR	A
	JR	NZ,.KIB
	LD	A,(UTIL_DEC32_SCRATCH+2)
	OR	A
	JR	NZ,.KIB
	LD	A,(UTIL_DEC32_SCRATCH+1)
	CP	4
	JR	NC,.KIB
	LD	HL,(UTIL_DEC32_SCRATCH)
	LD	DE,(UTIL_DEC32_SCRATCH+2)
	CALL	@UTIL.PRINT_DEC_32
	LD	HL,MSG_RATE_BPS
	CALL	PUTS
	JR	.DONE
.KIB
	LD	HL,(UTIL_DEC32_SCRATCH)
	LD	DE,(UTIL_DEC32_SCRATCH+2)
	LD	L,H
	LD	H,E
	LD	E,D
	LD	D,0
	SRL	E
	RR	H
	RR	L
	SRL	E
	RR	H
	RR	L
	CALL	@UTIL.PRINT_DEC_32
	LD	HL,MSG_RATE_KIB
	CALL	PUTS
.DONE
	CALL	CRLF
	OR	A
	RET
.TOO_SHORT
	SCF
	RET

; Best-effort teardown. Flags make it safe on every error path.
CLEANUP
	LD	A,(TCP_OPEN)
	OR	A
	JR	Z,.NET
	XOR	A
	LD	B,UNET_FN_CLOSE
	CALL	DO_CALL
	XOR	A
	LD	(TCP_OPEN),A
.NET
	LD	A,(NET_INITED)
	OR	A
	JR	Z,.DLL
	LD	B,UNET_FN_NETDONE
	CALL	DO_CALL
	XOR	A
	LD	(NET_INITED),A
.DLL
	LD	A,(DLL_LOADED)
	OR	A
	RET	Z
	LD	HL,(HANDLE)
	CALL	LIBMAN.l_free
	XOR	A
	LD	(DLL_LOADED),A
	RET

DUMP_LASTERR
	LD	A,(DLL_LOADED)
	OR	A
	RET	Z
	XOR	A
	LD	(HEADER_BUFF),A
	LD	DE,HEADER_BUFF
	LD	IX,HEADER_SIZE
	LD	B,UNET_FN_LASTERR
	CALL	DO_CALL
	OR	A
	RET	NZ
	LD	A,(HEADER_BUFF)
	OR	A
	RET	Z
	LD	HL,MSG_LASTERR
	CALL	PUTS
	LD	HL,HEADER_BUFF
	JP	PUTS_LN

DO_CALL
	LD	HL,(HANDLE)
	CALL	LIBMAN.l_call
	RET	NC
	; A dispatcher failure is not a UNET status. Convert it to hardware error
	; so all callers take a normal bounded error path.
	LD	A,NERR_HW
	RET

; Command line: exactly one URL token, or /?.
PARSE_CMD_LINE
	XOR	A
	LD	(HELP_REQUESTED),A
	LD	HL,(CMDLINE_PTR)
	LD	A,(HL)
	OR	A
	JR	Z,.ERR
	LD	B,A
	INC	HL
	CALL	SKIP_SPACES
	JR	C,.ERR
	LD	DE,URL_BUFF
	LD	C,URL_SIZE-1
	CALL	COPY_ARG
	JR	C,.ERR
	LD	HL,URL_BUFF
	LD	DE,SWITCH_HELP
	CALL	STREQ
	JR	NZ,.NOT_HELP
	LD	A,1
	LD	(HELP_REQUESTED),A
.NOT_HELP
	CALL	ONLY_SPACES_LEFT
	RET	NC
.ERR
	SCF
	RET

SKIP_SPACES
	LD	A,B
	OR	A
	JR	Z,.ERR
	LD	A,(HL)
	CP	0x21
	RET	NC
	INC	HL
	DJNZ	SKIP_SPACES
.ERR
	SCF
	RET

COPY_ARG
	LD	A,B
	OR	A
	JR	Z,.DONE
	LD	A,(HL)
	CP	0x21
	JR	C,.DONE
	LD	A,C
	OR	A
	JR	Z,.ERR
	LD	A,(HL)
	LD	(DE),A
	INC	HL
	INC	DE
	DEC	B
	DEC	C
	JR	COPY_ARG
.DONE
	XOR	A
	LD	(DE),A
	RET
.ERR
	SCF
	RET

ONLY_SPACES_LEFT
	LD	A,B
	OR	A
	RET	Z
	LD	A,(HL)
	CP	0x21
	JR	NC,.ERR
	INC	HL
	DJNZ	ONLY_SPACES_LEFT
	OR	A
	RET
.ERR
	SCF
	RET

PARSE_URL
	LD	HL,URL_BUFF
	LD	DE,HTTP_SCHEME
	CALL	STARTSWITH
	JP	NZ,.ERR
	LD	BC,7
	ADD	HL,BC
	LD	DE,HOST_BUFF
	LD	C,HOST_SIZE-1
.HOST
	LD	A,(HL)
	OR	A
	JR	Z,.HOST_DONE
	CP	'/'
	JR	Z,.HOST_DONE
	CP	':'
	JR	Z,.PORT_START
	LD	A,C
	OR	A
	JR	Z,.ERR
	LD	A,(HL)
	LD	(DE),A
	INC	HL
	INC	DE
	DEC	C
	JR	.HOST
.HOST_DONE
	XOR	A
	LD	(DE),A
	LD	A,(HOST_BUFF)
	OR	A
	JR	Z,.ERR
	PUSH	HL
	LD	HL,DEFAULT_PORT
	LD	DE,PORT_BUFF
	CALL	COPY_ASCIIZ
	POP	HL
	JR	.PATH_START
.PORT_START
	XOR	A
	LD	(DE),A
	INC	HL
	LD	DE,PORT_BUFF
	LD	C,PORT_SIZE-1
.PORT
	LD	A,(HL)
	OR	A
	JR	Z,.PORT_DONE
	CP	'/'
	JR	Z,.PORT_DONE
	CP	'0'
	JR	C,.ERR
	CP	'9'+1
	JR	NC,.ERR
	LD	A,C
	OR	A
	JR	Z,.ERR
	LD	A,(HL)
	LD	(DE),A
	INC	HL
	INC	DE
	DEC	C
	JR	.PORT
.PORT_DONE
	XOR	A
	LD	(DE),A
	LD	A,(PORT_BUFF)
	OR	A
	JR	Z,.ERR
.PATH_START
	LD	A,(HL)
	CP	'/'
	JR	Z,.COPY_PATH
	OR	A
	JR	NZ,.ERR
	LD	HL,DEFAULT_PATH
.COPY_PATH
	LD	DE,PATH_BUFF
	LD	C,PATH_SIZE-1
.PATH
	LD	A,(HL)
	OR	A
	JR	Z,.PATH_DONE
	LD	A,C
	OR	A
	JR	Z,.ERR
	LD	A,(HL)
	LD	(DE),A
	INC	HL
	INC	DE
	DEC	C
	JR	.PATH
.PATH_DONE
	XOR	A
	LD	(DE),A
	OR	A
	RET
.ERR
	SCF
	RET

BUILD_HTTP_REQUEST
	LD	HL,REQ_BUFF
	LD	DE,REQ_GET
	CALL	APPEND_STR
	LD	DE,PATH_BUFF
	CALL	APPEND_STR
	LD	DE,REQ_HOST
	CALL	APPEND_STR
	LD	DE,HOST_BUFF
	CALL	APPEND_STR
	PUSH	HL
	LD	HL,PORT_BUFF
	LD	DE,DEFAULT_PORT
	CALL	STREQ
	POP	HL
	JR	Z,.DEFAULT
	LD	DE,REQ_COLON
	CALL	APPEND_STR
	LD	DE,PORT_BUFF
	CALL	APPEND_STR
.DEFAULT
	LD	DE,REQ_END
	JP	APPEND_STR

APPEND_STR
	LD	A,(DE)
	LD	(HL),A
	OR	A
	RET	Z
	INC	HL
	INC	DE
	JR	APPEND_STR

COPY_ASCIIZ
	LD	A,(HL)
	LD	(DE),A
	OR	A
	RET	Z
	INC	HL
	INC	DE
	JR	COPY_ASCIIZ

STARTSWITH
	PUSH	HL
.LOOP
	LD	A,(DE)
	OR	A
	JR	Z,.MATCH
	CP	(HL)
	JR	NZ,.MISS
	INC	HL
	INC	DE
	JR	.LOOP
.MATCH
	POP	HL
	XOR	A
	RET
.MISS
	POP	HL
	LD	A,0xFF
	OR	A
	RET

STREQ
	LD	A,(DE)
	LD	C,A
	LD	A,(HL)
	CP	C
	RET	NZ
	AND	A
	RET	Z
	INC	HL
	INC	DE
	JR	STREQ

STRLEN
	LD	BC,0
.LOOP
	LD	A,(HL)
	OR	A
	RET	Z
	INC	HL
	INC	BC
	JR	.LOOP

PUTS
	PUSH	BC,DE,HL
	LD	C,DSS_PCHARS
	RST	DSS
	POP	HL,DE,BC
	RET

PUTS_LN
	CALL	PUTS
CRLF
	LD	HL,MSG_CRLF
	JR	PUTS

PUT_CHAR
	PUSH	AF,BC,DE,HL
	LD	C,DSS_PUTCHAR
	RST	DSS
	POP	HL,DE,BC,AF
	RET

PRINT_DEC_A
	LD	L,A
	LD	H,0
	LD	DE,0
	JP	@UTIL.PRINT_DEC_32

MSG_BANNER	DB "DLSPEED v",PACKAGE_VERSION," - UNET download throughput",0
MSG_USAGE	DB "Usage: DLSPEED.EXE http://host[:port]/path",13,10
		DB "       DLSPEED.EXE /?",13,10
		DB "Use at least 4 MiB for a stable RTC measurement.",0
MSG_SOURCE	DB "Source: ",0
MSG_LOADING	DB "Loading ",0
MSG_CONNECTING	DB "Connecting to ",0
MSG_WAIT_EDGE	DB "Waiting for RTC edge; transfer is silent until done...",0
MSG_RECEIVED	DB "Received: ",0
MSG_BYTES	DB " bytes",0
MSG_RATE_PREFIX	DB "  ",0
MSG_RATE_BYTES	DB " bytes in ",0
MSG_RATE_SEC	DB " sec",0
MSG_RATE_COMMA	DB ", ",0
MSG_RATE_BPS	DB " B/s",0
MSG_RATE_KIB	DB " KB/s",0
MSG_INTEGRITY_OK DB "Integrity: OK",0
MSG_SAMPLE_SHORT DB "Sample too short (less than one RTC second).",0
MSG_RTC_ERROR	DB "RTC second did not advance.",0
MSG_LOAD_ERROR	DB "Could not load UNETRTL.DLL.",0
MSG_ABI_ERROR	DB "UNET DLL has incompatible ABI or no TCP support.",0
MSG_NET_ERROR	DB "Network error #",0
MSG_RECV_ERROR	DB "Receive error #",0
MSG_HTTP_ERROR	DB "HTTP response error #",0
MSG_CANCELLED	DB "Measurement cancelled, error #",0
MSG_INCOMPLETE	DB "HTTP body ended early, error #",0
MSG_LASTERR	DB "lasterr: ",0
MSG_RESULT_OK	DB "RESULT OK",0
MSG_RESULT_FAIL	DB "RESULT FAIL",0
MSG_CRLF	DB 13,10,0

DLL_NAME	DB "UNETRTL.DLL",0
HTTP_SCHEME	DB "http://",0
DEFAULT_PORT	DB "80",0
DEFAULT_PATH	DB "/",0
SWITCH_HELP	DB "/?",0
REQ_GET		DB "GET ",0
REQ_HOST	DB " HTTP/1.1",13,10,"Host: ",0
REQ_COLON	DB ":",0
REQ_END		DB 13,10,"Accept-Encoding: identity",13,10
		DB "Connection: keep-alive",13,10,13,10,0

	ENDMODULE

	DEFINE USE_UTIL_TPUT
	DEFINE USE_UTIL_PRINT_DEC_32
	INCLUDE "libman13.asm"

; Runtime BSS is in the application's window, never in the EXE image.
DHTTP_BSS_BASE	EQU APP_BSS_BASE + 24
	INCLUDE "dlspeed_http.asm"
	INCLUDE "util.asm"

	MODULE MAIN
	ASSERT $ < LIBBSS_BASE

HANDLE		EQU APP_BSS_BASE + 0
CMDLINE_PTR	EQU APP_BSS_BASE + 2
DLL_LOADED	EQU APP_BSS_BASE + 4
NET_INITED	EQU APP_BSS_BASE + 5
TCP_OPEN	EQU APP_BSS_BASE + 6
HELP_REQUESTED	EQU APP_BSS_BASE + 7
API_STATUS	EQU APP_BSS_BASE + 8
ALIGN_SECOND	EQU APP_BSS_BASE + 10
ALIGN_LEFT	EQU APP_BSS_BASE + 13
STOP_TIME	EQU APP_BSS_BASE + 15
STOP_ELAPSED	EQU APP_BSS_BASE + 18

URL_BUFF	EQU DHTTP_BSS_BASE + DHTTP_BSS_SIZE
HOST_BUFF	EQU URL_BUFF + URL_SIZE
PORT_BUFF	EQU HOST_BUFF + HOST_SIZE
PATH_BUFF	EQU PORT_BUFF + PORT_SIZE
REQ_BUFF	EQU PATH_BUFF + PATH_SIZE
HEADER_BUFF	EQU REQ_BUFF + REQ_SIZE
RECV_BUFF	EQU HEADER_BUFF + HEADER_SIZE
BSS_END		EQU RECV_BUFF + RECV_SIZE
STACK_TOP	EQU 0xBFFF

	ASSERT BSS_END + 0x0100 <= STACK_TOP
	ASSERT RECV_BUFF >= 0x8000
	ASSERT RECV_BUFF + RECV_SIZE <= 0xC000
	ENDMODULE

	END MAIN.START
