; ======================================================
; PING.EXE - stage 6 of the Sprinter RTL8019AS network kit.
; ARP-resolves a hardcoded target IP, sends one ICMP echo
; request and waits for a matching echo reply.
;
; v0.1: hardcoded OUR_IP=192.168.7.2, TARGET_IP=192.168.7.1,
;       single ping. NET.CFG and command-line target arrive
;       in v0.2.
;
; Host setup (single-machine via feth pair):
;   sudo ifconfig feth0 create
;   sudo ifconfig feth1 create
;   sudo ifconfig feth0 peer feth1
;   sudo ifconfig feth0 up
;   sudo ifconfig feth1 inet 192.168.7.1/24 up
; macOS kernel will reply to ARP and ICMP for 192.168.7.1.
;
; Stage codes:
;   [P0] INIT
;   [P1] ARP WHO-HAS <target>
;   [P2] ARP REPLY MAC=...
;   [P3] BUILD ICMP
;   [P4] SEND
;   [P5] WAIT REPLY
;   [P6] REPLY id=... seq=...
;
; This version uses the RTL.INIT_NORMAL / RTL.SEND_FRAME /
; RTL.RING_HAS_PACKET / RTL.READ_PACKET helpers from the
; refactored library.
; ======================================================

EXE_VERSION		EQU 1

	DEVICE NOSLOT64K

	INCLUDE "macro.inc"
	INCLUDE "dss.inc"
	INCLUDE "rtl8019.inc"

; Pull in the high-level RTL + ARP + NETCFG helpers we need.
	DEFINE USE_RTL_INIT_NORMAL
	DEFINE USE_RTL_SEND_FRAME
	DEFINE USE_RTL_WAIT_PTX
	DEFINE USE_RTL_RING_HAS_PACKET
	DEFINE USE_RTL_READ_PACKET
	DEFINE USE_ARP_BUILD_REQUEST
	DEFINE USE_NETCFG_LOAD

ARP_OUTER	EQU 32			; ~15s ARP budget (arbitrary tick units)
ICMP_OUTER	EQU 32			; ~15s ICMP reply budget

ETH_TYPE_ARP	EQU 0x0806
ETH_TYPE_IPV4	EQU 0x0800
IP_PROTO_ICMP	EQU 1
ICMP_T_ECHO_REQ	EQU 8
ICMP_T_ECHO_REP	EQU 0

ARP_OP_REQUEST	EQU 1
ARP_OP_REPLY	EQU 2

; -- frame sizes --
ARP_FRAME_LEN	EQU 60			; padded
IP_HDR_LEN	EQU 20
ICMP_HDR_LEN	EQU 8
ICMP_PAYLOAD_LEN EQU 32
ICMP_FRAME_LEN	EQU 14 + IP_HDR_LEN + ICMP_HDR_LEN + ICMP_PAYLOAD_LEN	; 74

ECHO_ID_HI	EQU 0x12
ECHO_ID_LO	EQU 0x34
ECHO_SEQ_HI	EQU 0x00
ECHO_SEQ_LO	EQU 0x01

	MODULE MAIN

	ORG 0x8080

EXE_HEADER
	DB "EXE"
	DB EXE_VERSION
	DW 0x0080
	DW 0
	DW 0
	DW 0
	DW 0
	DW 0
	DW START
	DW START
	DW STACK_TOP
	DS 106, 0

	ORG 0x8100
@STACK_TOP

START
	PRINTLN MSG_BANNER

	; Read NET.CFG (defaults applied if file missing).
	CALL	@NETCFG.LOAD

	LD	A,1
	LD	(@ISA.ISA_SLOT),A
	CALL	@ISA.ISA_OPEN

	; [P0] INIT
	PRINT MSG_P0
	CALL	@RTL.RESET
	JP	C,RESET_FAIL
	LD	HL,@NETCFG.OUR_MAC
	LD	A,RCR_AB
	CALL	@RTL.INIT_NORMAL
	; ARP module setup -- point at NETCFG fields.
	LD	HL,@NETCFG.OUR_MAC
	LD	(@ARP.OUR_MAC_PTR),HL
	LD	HL,@NETCFG.OUR_IP
	LD	(@ARP.OUR_IP_PTR),HL
	PRINTLN MSG_OK

	PRINT MSG_PING_HDR
	LD	HL,TARGET_IP
	CALL	PRINT_IPV4
	PRINT MSG_FROM
	LD	HL,@NETCFG.OUR_IP
	CALL	PRINT_IPV4
	PRINT LINE_END

	; [P1] ARP
	PRINT MSG_P1
	LD	HL,TARGET_IP
	CALL	PRINT_IPV4
	PRINT LINE_END

	LD	DE,TX_BUF
	LD	HL,TARGET_IP
	CALL	@ARP.BUILD_REQUEST
	LD	HL,TX_BUF
	LD	BC,ARP_FRAME_LEN
	CALL	@RTL.SEND_FRAME
	JP	C,SEND_FAIL

	LD	HL,ARP_OUTER
	LD	(OUTER_LEFT),HL
	CALL	WAIT_FOR_ARP_REPLY
	JP	C,ARP_TIMEOUT

	; [P2] ARP REPLY
	PRINT MSG_P2
	LD	HL,TARGET_MAC
	CALL	@UTIL.PRINT_MAC
	PRINT LINE_END

	; [P3] BUILD ICMP
	CALL	BUILD_ICMP_ECHO
	PRINTLN MSG_P3

	; [P4] SEND
	PRINT MSG_P4
	LD	HL,TX_BUF
	LD	BC,ICMP_FRAME_LEN
	CALL	@RTL.SEND_FRAME
	JP	C,SEND_FAIL
	PRINTLN MSG_OK

	; [P5] WAIT REPLY
	PRINTLN MSG_P5
	LD	HL,ICMP_OUTER
	LD	(OUTER_LEFT),HL
	CALL	WAIT_FOR_ICMP_REPLY
	JP	C,ICMP_TIMEOUT

	; [P6] REPLY id=xxxx seq=xxxx
	PRINT MSG_P6_ID
	LD	A,(REPLY_ID + 0)
	CALL	@UTIL.PRINT_HEX_A
	LD	A,(REPLY_ID + 1)
	CALL	@UTIL.PRINT_HEX_A
	PRINT MSG_SEQ_EQ
	LD	A,(REPLY_SEQ + 0)
	CALL	@UTIL.PRINT_HEX_A
	LD	A,(REPLY_SEQ + 1)
	CALL	@UTIL.PRINT_HEX_A
	PRINT LINE_END

	PRINTLN MSG_RESULT_OK
	CALL	@ISA.ISA_CLOSE
	DSS_RETURN EX_OK


RESET_FAIL
	PRINT LINE_END
	PRINTLN MSG_E_RESET
	JP	FAIL_NIC

SEND_FAIL
	PRINT LINE_END
	PRINTLN MSG_E_SEND
	JP	FAIL_NIC

ARP_TIMEOUT
	PRINTLN MSG_E_ARP
	JP	FAIL_NIC

ICMP_TIMEOUT
	PRINTLN MSG_E_ICMP
	JP	FAIL_NIC

FAIL_NIC
	CALL	@RTL.SNAPSHOT_REGS
	CALL	PRINT_REG_DUMP
	PRINTLN MSG_RESULT_FAIL
	CALL	@ISA.ISA_CLOSE
	DSS_RETURN EX_NIC_ERR


; ------------------------------------------------------
; BUILD_ICMP_ECHO: 74-byte ICMP echo request frame in TX_BUF.
; ------------------------------------------------------
BUILD_ICMP_ECHO
	LD	DE,TX_BUF
	LD	HL,TARGET_MAC
	LD	BC,6
	LDIR
	LD	HL,@NETCFG.OUR_MAC
	LD	BC,6
	LDIR
	LD	A,HIGH ETH_TYPE_IPV4
	LD	(DE),A
	INC	DE
	LD	A,LOW ETH_TYPE_IPV4
	LD	(DE),A
	INC	DE

	LD	A,0x45
	LD	(DE),A
	INC	DE
	XOR	A
	LD	(DE),A
	INC	DE
	LD	A,HIGH (IP_HDR_LEN + ICMP_HDR_LEN + ICMP_PAYLOAD_LEN)
	LD	(DE),A
	INC	DE
	LD	A,LOW (IP_HDR_LEN + ICMP_HDR_LEN + ICMP_PAYLOAD_LEN)
	LD	(DE),A
	INC	DE
	XOR	A
	LD	(DE),A
	INC	DE
	LD	A,1
	LD	(DE),A
	INC	DE
	XOR	A
	LD	(DE),A
	INC	DE
	LD	(DE),A
	INC	DE
	LD	A,64
	LD	(DE),A
	INC	DE
	LD	A,IP_PROTO_ICMP
	LD	(DE),A
	INC	DE
	XOR	A
	LD	(DE),A
	INC	DE
	LD	(DE),A
	INC	DE
	LD	HL,@NETCFG.OUR_IP
	LD	BC,4
	LDIR
	LD	HL,TARGET_IP
	LD	BC,4
	LDIR

	LD	A,ICMP_T_ECHO_REQ
	LD	(DE),A
	INC	DE
	XOR	A
	LD	(DE),A
	INC	DE
	XOR	A
	LD	(DE),A
	INC	DE
	LD	(DE),A
	INC	DE
	LD	A,ECHO_ID_HI
	LD	(DE),A
	INC	DE
	LD	A,ECHO_ID_LO
	LD	(DE),A
	INC	DE
	LD	A,ECHO_SEQ_HI
	LD	(DE),A
	INC	DE
	LD	A,ECHO_SEQ_LO
	LD	(DE),A
	INC	DE

	LD	B,ICMP_PAYLOAD_LEN
	XOR	A
.PAY
	LD	(DE),A
	INC	DE
	INC	A
	DJNZ	.PAY

	; IP checksum over TX_BUF+14, length 20.
	PUSH	IX
	LD	IX,TX_BUF + 14
	LD	BC,IP_HDR_LEN
	CALL	@UTIL.CHECKSUM
	POP	IX
	LD	A,H
	LD	(TX_BUF + 14 + 10),A
	LD	A,L
	LD	(TX_BUF + 14 + 11),A

	; ICMP checksum over TX_BUF+34, length 40.
	PUSH	IX
	LD	IX,TX_BUF + 14 + IP_HDR_LEN
	LD	BC,ICMP_HDR_LEN + ICMP_PAYLOAD_LEN
	CALL	@UTIL.CHECKSUM
	POP	IX
	LD	A,H
	LD	(TX_BUF + 14 + IP_HDR_LEN + 2),A
	LD	A,L
	LD	(TX_BUF + 14 + IP_HDR_LEN + 3),A
	RET


; ------------------------------------------------------
; WAIT_FOR_ARP_REPLY: spin on RTL.RING_HAS_PACKET +
; RTL.READ_PACKET, drop anything that isn't a matching ARP
; reply, populate TARGET_MAC on match.
;   OUTER_LEFT must be set before call.
;   Out: CF=0 OK, CF=1 timeout.
; ------------------------------------------------------
WAIT_FOR_ARP_REPLY
.MAIN
	CALL	@RTL.RING_HAS_PACKET
	JR	NZ,.HAVE
	LD	BC,0
.WAIT
	CALL	@RTL.RING_HAS_PACKET
	JR	NZ,.HAVE
	DEC	BC
	LD	A,B
	OR	C
	JR	NZ,.WAIT
	LD	HL,(OUTER_LEFT)
	DEC	HL
	LD	(OUTER_LEFT),HL
	LD	A,H
	OR	L
	JR	Z,.TIMEOUT
	JR	.MAIN
.HAVE
	LD	HL,RX_HDR
	LD	DE,RX_BUF
	LD	BC,RX_BUF_SIZE
	CALL	@RTL.READ_PACKET
	JR	C,.MAIN			; DMA error, drop and continue
	; Filter: ARP reply, sender_ip == TARGET_IP
	LD	A,(RX_BUF + 12)
	CP	HIGH ETH_TYPE_ARP
	JR	NZ,.MAIN
	LD	A,(RX_BUF + 13)
	CP	LOW ETH_TYPE_ARP
	JR	NZ,.MAIN
	LD	A,(RX_BUF + 14 + 6)
	OR	A
	JR	NZ,.MAIN
	LD	A,(RX_BUF + 14 + 7)
	CP	ARP_OP_REPLY
	JR	NZ,.MAIN
	LD	HL,RX_BUF + 14 + 14
	LD	DE,TARGET_IP
	LD	B,4
.CMPIP
	LD	A,(DE)
	CP	(HL)
	JR	NZ,.MAIN
	INC	HL
	INC	DE
	DJNZ	.CMPIP
	; Match: copy sender MAC to TARGET_MAC.
	LD	HL,RX_BUF + 14 + 8
	LD	DE,TARGET_MAC
	LD	BC,6
	LDIR
	OR	A
	RET
.TIMEOUT
	SCF
	RET


; ------------------------------------------------------
; WAIT_FOR_ICMP_REPLY: same loop pattern, ICMP echo-reply
; filter, capture id/seq.
;   Out: CF=0 OK, CF=1 timeout.
; ------------------------------------------------------
WAIT_FOR_ICMP_REPLY
.MAIN
	CALL	@RTL.RING_HAS_PACKET
	JR	NZ,.HAVE
	LD	BC,0
.WAIT
	CALL	@RTL.RING_HAS_PACKET
	JR	NZ,.HAVE
	DEC	BC
	LD	A,B
	OR	C
	JR	NZ,.WAIT
	LD	HL,(OUTER_LEFT)
	DEC	HL
	LD	(OUTER_LEFT),HL
	LD	A,H
	OR	L
	JR	Z,.TIMEOUT
	JR	.MAIN
.HAVE
	LD	HL,RX_HDR
	LD	DE,RX_BUF
	LD	BC,RX_BUF_SIZE
	CALL	@RTL.READ_PACKET
	JR	C,.MAIN
	; Filter: IPv4 / ICMP / echo reply / matching id.
	LD	A,(RX_BUF + 12)
	CP	HIGH ETH_TYPE_IPV4
	JR	NZ,.MAIN
	LD	A,(RX_BUF + 13)
	CP	LOW ETH_TYPE_IPV4
	JR	NZ,.MAIN
	LD	A,(RX_BUF + 14)
	CP	0x45
	JR	NZ,.MAIN
	LD	A,(RX_BUF + 14 + 9)
	CP	IP_PROTO_ICMP
	JR	NZ,.MAIN
	LD	HL,RX_BUF + 14 + 12
	LD	DE,TARGET_IP
	LD	B,4
.CMPSRC
	LD	A,(DE)
	CP	(HL)
	JR	NZ,.MAIN
	INC	HL
	INC	DE
	DJNZ	.CMPSRC
	LD	A,(RX_BUF + 14 + IP_HDR_LEN + 0)
	CP	ICMP_T_ECHO_REP
	JR	NZ,.MAIN
	LD	A,(RX_BUF + 14 + IP_HDR_LEN + 4)
	CP	ECHO_ID_HI
	JR	NZ,.MAIN
	LD	A,(RX_BUF + 14 + IP_HDR_LEN + 5)
	CP	ECHO_ID_LO
	JR	NZ,.MAIN
	LD	A,(RX_BUF + 14 + IP_HDR_LEN + 4)
	LD	(REPLY_ID + 0),A
	LD	A,(RX_BUF + 14 + IP_HDR_LEN + 5)
	LD	(REPLY_ID + 1),A
	LD	A,(RX_BUF + 14 + IP_HDR_LEN + 6)
	LD	(REPLY_SEQ + 0),A
	LD	A,(RX_BUF + 14 + IP_HDR_LEN + 7)
	LD	(REPLY_SEQ + 1),A
	OR	A
	RET
.TIMEOUT
	SCF
	RET


; ------------------------------------------------------
; PRINT_IPV4 / PRINT_DEC_A / PUTCHAR / PRINT_REG_DUMP
; (app-local helpers; could be lifted to lib later)
; ------------------------------------------------------
PRINT_IPV4
	PUSH	HL,BC
	LD	B,4
.LP
	LD	A,(HL)
	CALL	PRINT_DEC_A
	INC	HL
	DEC	B
	JR	Z,.DONE
	PUSH	BC
	LD	A,'.'
	LD	C,DSS_PUTCHAR
	RST	DSS
	POP	BC
	JR	.LP
.DONE
	POP	BC,HL
	RET


PRINT_DEC_A
	PUSH	AF,BC,DE,HL
	LD	C,A
	LD	HL,DEC_BUF + 3
	LD	(HL),0
.LP
	LD	A,C
	LD	B,0
.SUB
	CP	10
	JR	C,.GOT
	SUB	10
	INC	B
	JR	.SUB
.GOT
	ADD	A,'0'
	DEC	HL
	LD	(HL),A
	LD	C,B
	LD	A,B
	OR	A
	JR	NZ,.LP
	LD	C,DSS_PCHARS
	RST	DSS
	POP	HL,DE,BC,AF
	RET

DEC_BUF		DS 4,0


PUTCHAR
	PUSH	AF,BC
	LD	C,DSS_PUTCHAR
	RST	DSS
	POP	BC,AF
	RET


PRINT_REG_DUMP
	PRINT MSG_REGS
	LD	HL,REG_NAMES
	LD	DE,@RTL.REG_SNAPSHOT
	LD	B,@RTL.REG_SNAPSHOT_LEN
.LP
	PUSH	BC,DE
.NCHR
	LD	A,(HL)
	INC	HL
	OR	A
	JR	Z,.NDONE
	CALL	PUTCHAR
	JR	.NCHR
.NDONE
	LD	A,'='
	CALL	PUTCHAR
	POP	DE,BC
	LD	A,(DE)
	CALL	@UTIL.PRINT_HEX_A
	LD	A,' '
	CALL	PUTCHAR
	INC	DE
	DJNZ	.LP
	PRINT LINE_END
	RET

REG_NAMES
	DB "CR",0
	DB "ISR",0
	DB "DCR",0
	DB "RCR",0
	DB "TCR",0
	DB "IMR",0
	DB "PSTART",0
	DB "PSTOP",0
	DB "BNRY",0
	DB "CURR",0


; ------- in-EXE data -------
; OUR_MAC / OUR_IP now live in @NETCFG.* (loaded by NETCFG.LOAD).
TARGET_IP	DB 192, 168, 7, 1
TARGET_MAC	DB 0,0,0,0,0,0
OUTER_LEFT	DW 0
REPLY_ID	DW 0
REPLY_SEQ	DW 0


; ------- messages -------
MSG_BANNER	DB "RTL8019AS PING v0.1",0
MSG_PING_HDR	DB "PING ",0
MSG_FROM	DB " from ",0
MSG_P0		DB "[P0] INIT ",0
MSG_OK		DB "OK",0
MSG_P1		DB "[P1] ARP WHO-HAS ",0
MSG_P2		DB "[P2] ARP REPLY MAC=",0
MSG_P3		DB "[P3] BUILD ICMP OK",0
MSG_P4		DB "[P4] SEND ",0
MSG_P5		DB "[P5] WAIT REPLY",0
MSG_P6_ID	DB "[P6] REPLY id=",0
MSG_SEQ_EQ	DB " seq=",0
MSG_REGS	DB "REGS ",0
MSG_RESULT_OK	DB "RESULT OK",0
MSG_RESULT_FAIL	DB "RESULT FAIL",0
MSG_E_RESET	DB "[E60] RESET timeout",0
MSG_E_SEND	DB "[E61] DMA write or PTX timeout",0
MSG_E_ARP	DB "[E62] ARP reply timeout",0
MSG_E_ICMP	DB "[E63] ICMP echo reply timeout",0
LINE_END	DB 13,10,0

	ENDMODULE


	; netcfg_lib transitively DEFINEs USE_UTIL_* helpers it needs,
	; so it must be included BEFORE util.asm.
	INCLUDE "netcfg_lib.asm"
	INCLUDE "isa.asm"
	INCLUDE "util.asm"
	INCLUDE "rtl8019.asm"
	INCLUDE "arp_lib.asm"


PING_IMAGE_END

RX_BUF_SIZE	EQU 1518

	MODULE MAIN

TX_BUF		EQU PING_IMAGE_END
RX_HDR		EQU TX_BUF + ICMP_FRAME_LEN
RX_BUF		EQU RX_HDR + 4
PING_BSS_END	EQU RX_BUF + RX_BUF_SIZE

	ENDMODULE

	END MAIN.START
