; ======================================================
; UDPTEST.EXE - stage 7 of the Sprinter RTL8019AS network kit.
; ARP-resolves a hardcoded target IP, sends one UDP datagram
; with a fixed payload, waits for a matching echo reply from
; tools/dev/udp_echo.py running on the host.
;
; v0.1: hardcoded OUR_IP=192.168.7.2, TARGET_IP=192.168.7.1,
;       TARGET_PORT=7777, OUR_PORT=0xC000, payload="SPRINTER UDP".
;       NET.CFG / cmdline target arrive in v0.2.
;
; Host setup (single-machine via feth pair):
;   sudo ifconfig feth0 create
;   sudo ifconfig feth1 create
;   sudo ifconfig feth0 peer feth1
;   sudo ifconfig feth0 up
;   sudo ifconfig feth1 inet 192.168.7.1/24 up
;   sudo python3 tools/dev/udp_echo.py
;
; Stage codes:
;   [U0] INIT
;   [U1] ARP WHO-HAS <target>
;   [U2] ARP REPLY MAC=...
;   [U3] BUILD UDP
;   [U4] SEND
;   [U5] WAIT REPLY
;   [U6] REPLY len=xxxx data=...
; ======================================================

EXE_VERSION		EQU 1

	DEVICE NOSLOT64K

	INCLUDE "macro.inc"
	INCLUDE "dss.inc"
	INCLUDE "memmap.inc"
	INCLUDE "rtl8019.inc"

	DEFINE USE_RTL_INIT_NORMAL
	DEFINE USE_RTL_SEND_FRAME
	DEFINE USE_RTL_WAIT_PTX
	DEFINE USE_RTL_RING_HAS_PACKET
	DEFINE USE_RTL_READ_PACKET
	DEFINE USE_ARP_BUILD_REQUEST
	DEFINE USE_NETENV
	DEFINE USE_CMDL
	DEFINE USE_RESOLVE
	DEFINE CMDLINE_AT_LARGE

ARP_TIMEOUT_MS	EQU 3000
UDP_TIMEOUT_MS	EQU 3000
SCAN_C		EQU 0xAC

ETH_TYPE_ARP	EQU 0x0806
ETH_TYPE_IPV4	EQU 0x0800
IP_PROTO_UDP	EQU 17

ARP_OP_REQUEST	EQU 1
ARP_OP_REPLY	EQU 2

ARP_FRAME_LEN	EQU 60
IP_HDR_LEN	EQU 20
UDP_HDR_LEN	EQU 8
UDP_PAYLOAD_LEN	EQU 16
UDP_FRAME_LEN	EQU 14 + IP_HDR_LEN + UDP_HDR_LEN + UDP_PAYLOAD_LEN	; 58

OUR_PORT_HI	EQU 0xC0
OUR_PORT_LO	EQU 0x00

	MODULE MAIN

	ORG 0x4100

EXE_HEADER
	DB "EXE"
	DB EXE_VERSION
	DW 0x0100
	DW 0
	DW 0
	DW 0
	DW 0
	DW 0
	DW START
	DW START
	DW 0xBFFF
	DS 234, 0

	ORG 0x4200

START
	PRINTLN MSG_BANNER

	XOR	A
	LD	(CANCELLED),A

	CALL	@CMDL.PARSE
	CALL	@CMDL.IS_HELP
	JP	NC,SHOW_HELP

	; positional 0: host (IPv4 literal or hostname)
	LD	B,0
	CALL	@CMDL.GET_POSITIONAL
	JP	C,USAGE_ERROR
	LD	(TARGET_HOST_PTR),HL

	; positional 1: port (1..65535)
	LD	B,1
	CALL	@CMDL.GET_POSITIONAL
	JP	C,USAGE_ERROR
	CALL	@CMDL.PARSE_U16
	JP	C,USAGE_ERROR
	LD	A,H
	OR	L
	JP	Z,USAGE_ERROR			; port 0 not allowed
	LD	A,H
	LD	(TARGET_PORT_HI),A
	LD	A,L
	LD	(TARGET_PORT_LO),A

	; Pull NET_IP / NET_MAC from env.
	LD	HL,N_NET_IP
	LD	DE,OUR_IP
	CALL	@NETENV.REQUIRE_IP
	LD	HL,N_NET_MAC
	LD	DE,OUR_MAC
	CALL	@NETENV.REQUIRE_MAC

	; Init NIC.
	LD	A,1
	LD	(@ISA.ISA_SLOT),A
	CALL	@ISA.ISA_OPEN
	CALL	@RTL.RESET
	JP	C,RESET_FAIL
	LD	HL,OUR_MAC
	LD	A,RCR_AB
	CALL	@RTL.INIT_NORMAL
	LD	HL,OUR_MAC
	LD	(@ARP.OUR_MAC_PTR),HL
	LD	HL,OUR_IP
	LD	(@ARP.OUR_IP_PTR),HL

	; Resolve target host (literal IPv4 or hostname).
	LD	HL,(TARGET_HOST_PTR)
	LD	DE,TARGET_IP
	CALL	@RESOLVE.HOST
	JP	C,RESOLVE_FAIL

	; "Sending UDP to X:port from Y"
	PRINT LINE_END
	PRINT MSG_SENDING_TO
	LD	HL,TARGET_IP
	CALL	PRINT_IPV4
	LD	A,':'
	CALL	PUTCHAR
	LD	A,(TARGET_PORT_HI)
	LD	H,A
	LD	A,(TARGET_PORT_LO)
	LD	L,A
	CALL	PRINT_DEC_HL
	PRINT MSG_FROM_HOST
	LD	HL,OUR_IP
	CALL	PRINT_IPV4
	PRINT LINE_END

	; ARP resolve.
	LD	DE,TX_BUF
	LD	HL,TARGET_IP
	CALL	@ARP.BUILD_REQUEST
	LD	HL,TX_BUF
	LD	BC,ARP_FRAME_LEN
	CALL	@RTL.SEND_FRAME
	JP	C,SEND_FAIL
	LD	HL,ARP_TIMEOUT_MS
	LD	(TIMEOUT_MS_LEFT),HL
	CALL	WAIT_FOR_ARP_REPLY
	JP	C,ARP_TIMEOUT

	; Build & send UDP datagram.
	CALL	BUILD_UDP_DATAGRAM
	LD	HL,TX_BUF
	LD	BC,UDP_FRAME_LEN
	CALL	@RTL.SEND_FRAME
	JP	C,SEND_FAIL

	; Wait reply.
	LD	HL,UDP_TIMEOUT_MS
	LD	(TIMEOUT_MS_LEFT),HL
	CALL	WAIT_FOR_UDP_REPLY
	JP	C,UDP_TIMEOUT

	; "Reply: len=N data=..."
	PRINT MSG_REPLY_LEN
	LD	HL,(REPLY_LEN)
	CALL	PRINT_DEC_HL
	PRINT MSG_DATA_EQ
	LD	HL,REPLY_BUF
	LD	BC,(REPLY_LEN)
	CALL	PRINT_TEXT
	PRINT LINE_END

	CALL	@ISA.ISA_CLOSE
	JP	@UTIL.EXIT_OK


RESET_FAIL
	PRINT LINE_END
	PRINTLN MSG_E_RESET
	JP	FAIL_NIC

SEND_FAIL
	PRINT LINE_END
	PRINTLN MSG_E_SEND
	JP	FAIL_NIC

ARP_TIMEOUT
	LD	A,(CANCELLED)
	OR	A
	JR	NZ,.CANCEL
	PRINTLN MSG_E_ARP
	JP	FAIL_NIC
.CANCEL
	PRINTLN MSG_ABORTED
	CALL	@ISA.ISA_CLOSE
	LD	B,EX_NET_ERR
	JP	@UTIL.EXIT_FAIL

UDP_TIMEOUT
	LD	A,(CANCELLED)
	OR	A
	JR	NZ,.CANCEL
	PRINTLN MSG_E_UDP
	JP	FAIL_NIC
.CANCEL
	PRINTLN MSG_ABORTED
	CALL	@ISA.ISA_CLOSE
	LD	B,EX_NET_ERR
	JP	@UTIL.EXIT_FAIL

FAIL_NIC
	CALL	@RTL.SNAPSHOT_REGS
	CALL	PRINT_REG_DUMP
	CALL	@ISA.ISA_CLOSE
	LD	B,EX_NET_ERR
	JP	@UTIL.EXIT_FAIL


RESOLVE_FAIL
	LD	A,(@RESOLVE.LAST_FAIL)
	CP	1
	JR	Z,.USG
	CP	2
	JR	Z,.NDNS
	CP	3
	JR	Z,.NGW
	CP	7
	JR	Z,.CAN
	PRINTLN MSG_E_RESOLVE
	CALL	@ISA.ISA_CLOSE
	LD	B,EX_NET_ERR
	JP	@UTIL.EXIT_FAIL
.USG
	CALL	@ISA.ISA_CLOSE
	JP	USAGE_ERROR
.NDNS
	PRINTLN MSG_E_NO_DNS1
	CALL	@ISA.ISA_CLOSE
	LD	B,4
	JP	@UTIL.EXIT_FAIL
.NGW
	PRINTLN MSG_E_NO_GW
	CALL	@ISA.ISA_CLOSE
	LD	B,4
	JP	@UTIL.EXIT_FAIL
.CAN
	PRINTLN MSG_ABORTED
	CALL	@ISA.ISA_CLOSE
	LD	B,EX_NET_ERR
	JP	@UTIL.EXIT_FAIL


SHOW_HELP
	LD	HL,MSG_HELP
	LD	C,DSS_PCHARS
	RST	DSS
	JP	@UTIL.EXIT_OK


USAGE_ERROR
	PRINTLN MSG_USAGE_ERR
	LD	HL,MSG_HELP
	LD	C,DSS_PCHARS
	RST	DSS
	LD	B,1
	JP	@UTIL.EXIT_FAIL


; ------------------------------------------------------
; TICK_AND_CHECK_KEY: ~1 ms wait + Esc/Ctrl+C poll.
; SCANKEY may switch memory pages -> close ISA around it.
;   Out: CF=0 normal; CF=1 cancelled (CANCELLED set).
; ------------------------------------------------------
TICK_AND_CHECK_KEY
	CALL	@UTIL.DELAY_1MS
	CALL	@ISA.ISA_CLOSE
	LD	C,DSS_SCANKEY
	RST	DSS
	JR	Z,.NO_KEY
	LD	A,E
	CP	0x1B
	JR	Z,.CANCEL
	LD	A,B
	AND	KB_CTRL | KB_L_CTRL | KB_R_CTRL
	JR	Z,.NO_KEY
	LD	A,D
	CP	SCAN_C
	JR	Z,.CANCEL
	JR	.NO_KEY
.CANCEL
	LD	A,1
	LD	(CANCELLED),A
	CALL	@ISA.ISA_OPEN
	SCF
	RET
.NO_KEY
	CALL	@ISA.ISA_OPEN
	OR	A
	RET


; ------------------------------------------------------
; PRINT_DEC_HL: print HL as unsigned decimal, no leading zeros.
; Trashes A,BC,DE.
; ------------------------------------------------------
PRINT_DEC_HL
	PUSH	HL
	LD	A,H
	OR	L
	JR	NZ,.NZ
	LD	A,'0'
	CALL	PUTCHAR
	POP	HL
	RET
.NZ
	LD	B,0			; B = digit count
.LP
	LD	A,H
	OR	L
	JR	Z,.PRT
	PUSH	BC			; DIV_HL_10 trashes BC
	CALL	DIV_HL_10
	POP	BC
	ADD	A,'0'
	PUSH	AF
	INC	B
	JR	.LP
.PRT
	LD	A,B
	OR	A
	JR	Z,.DONE
.OUTL
	POP	AF
	CALL	PUTCHAR
	DJNZ	.OUTL
.DONE
	POP	HL
	RET

; DIV_HL_10: HL = HL / 10; A = HL mod 10. Trashes BC, DE.
DIV_HL_10
	LD	BC,0
	LD	DE,16
.LP
	ADD	HL,HL
	RL	C
	LD	A,C
	CP	10
	JR	C,.NS
	SUB	10
	LD	C,A
	INC	L
.NS
	DEC	E
	JR	NZ,.LP
	LD	A,C
	RET


; ------------------------------------------------------
; BUILD_UDP_DATAGRAM: 58-byte UDP-over-IPv4 frame in TX_BUF.
;   ETH (14) + IPv4 (20) + UDP (8) + payload (16).
;   IP checksum is computed; UDP checksum is left as 0
;   (allowed in IPv4 to skip).
; ------------------------------------------------------
BUILD_UDP_DATAGRAM
	; Ethernet
	LD	DE,TX_BUF
	LD	HL,TARGET_MAC
	LD	BC,6
	LDIR
	LD	HL,OUR_MAC
	LD	BC,6
	LDIR
	LD	A,HIGH ETH_TYPE_IPV4
	LD	(DE),A
	INC	DE
	LD	A,LOW ETH_TYPE_IPV4
	LD	(DE),A
	INC	DE

	; IPv4 header
	LD	A,0x45
	LD	(DE),A
	INC	DE
	XOR	A
	LD	(DE),A
	INC	DE
	LD	A,HIGH (IP_HDR_LEN + UDP_HDR_LEN + UDP_PAYLOAD_LEN)
	LD	(DE),A
	INC	DE
	LD	A,LOW (IP_HDR_LEN + UDP_HDR_LEN + UDP_PAYLOAD_LEN)
	LD	(DE),A
	INC	DE
	XOR	A
	LD	(DE),A
	INC	DE
	LD	A,1
	LD	(DE),A
	INC	DE
	XOR	A
	LD	(DE),A
	INC	DE
	LD	(DE),A
	INC	DE
	LD	A,64
	LD	(DE),A
	INC	DE
	LD	A,IP_PROTO_UDP
	LD	(DE),A
	INC	DE
	XOR	A
	LD	(DE),A			; csum placeholder
	INC	DE
	LD	(DE),A
	INC	DE
	LD	HL,OUR_IP
	LD	BC,4
	LDIR
	LD	HL,TARGET_IP
	LD	BC,4
	LDIR

	; UDP header
	LD	A,OUR_PORT_HI
	LD	(DE),A
	INC	DE
	LD	A,OUR_PORT_LO
	LD	(DE),A
	INC	DE
	LD	A,(TARGET_PORT_HI)
	LD	(DE),A
	INC	DE
	LD	A,(TARGET_PORT_LO)
	LD	(DE),A
	INC	DE
	; UDP length = UDP header + payload (BE)
	LD	A,HIGH (UDP_HDR_LEN + UDP_PAYLOAD_LEN)
	LD	(DE),A
	INC	DE
	LD	A,LOW (UDP_HDR_LEN + UDP_PAYLOAD_LEN)
	LD	(DE),A
	INC	DE
	; UDP checksum = 0 (disabled, allowed in IPv4)
	XOR	A
	LD	(DE),A
	INC	DE
	LD	(DE),A
	INC	DE

	; Payload (16 bytes, copy from PAYLOAD)
	LD	HL,PAYLOAD
	LD	BC,UDP_PAYLOAD_LEN
	LDIR

	; Compute IP checksum over TX_BUF+14, length 20.
	PUSH	IX
	LD	IX,TX_BUF + 14
	LD	BC,IP_HDR_LEN
	CALL	@UTIL.CHECKSUM
	POP	IX
	LD	A,H
	LD	(TX_BUF + 14 + 10),A
	LD	A,L
	LD	(TX_BUF + 14 + 11),A
	RET


; ------------------------------------------------------
; WAIT_FOR_ARP_REPLY: identical pattern to PING / ARP.
; ------------------------------------------------------
WAIT_FOR_ARP_REPLY
.LP
	CALL	@RTL.RING_HAS_PACKET
	JR	NZ,.HAVE
	CALL	TICK_AND_CHECK_KEY
	JR	C,.TIMEOUT
	LD	HL,(TIMEOUT_MS_LEFT)
	DEC	HL
	LD	(TIMEOUT_MS_LEFT),HL
	LD	A,H
	OR	L
	JR	NZ,.LP
	JR	.TIMEOUT
.HAVE
	LD	HL,RX_HDR
	LD	DE,RX_BUF
	LD	BC,RX_BUF_SIZE
	CALL	@RTL.READ_PACKET
	JR	C,.LP
	LD	A,(RX_BUF + 12)
	CP	HIGH ETH_TYPE_ARP
	JR	NZ,.LP
	LD	A,(RX_BUF + 13)
	CP	LOW ETH_TYPE_ARP
	JR	NZ,.LP
	LD	A,(RX_BUF + 14 + 6)
	OR	A
	JR	NZ,.LP
	LD	A,(RX_BUF + 14 + 7)
	CP	ARP_OP_REPLY
	JR	NZ,.LP
	LD	HL,RX_BUF + 14 + 14
	LD	DE,TARGET_IP
	LD	B,4
.CMPIP
	LD	A,(DE)
	CP	(HL)
	JR	NZ,.LP
	INC	HL
	INC	DE
	DJNZ	.CMPIP
	LD	HL,RX_BUF + 14 + 8
	LD	DE,TARGET_MAC
	LD	BC,6
	LDIR
	OR	A
	RET
.TIMEOUT
	SCF
	RET


; ------------------------------------------------------
; WAIT_FOR_UDP_REPLY: filter for UDP echo on our port.
; Captures payload bytes into REPLY_BUF and length into REPLY_LEN.
; ------------------------------------------------------
WAIT_FOR_UDP_REPLY
.LP
	CALL	@RTL.RING_HAS_PACKET
	JR	NZ,.HAVE
	CALL	TICK_AND_CHECK_KEY
	JP	C,.TIMEOUT
	LD	HL,(TIMEOUT_MS_LEFT)
	DEC	HL
	LD	(TIMEOUT_MS_LEFT),HL
	LD	A,H
	OR	L
	JP	NZ,.LP
	JP	.TIMEOUT
.HAVE
	LD	HL,RX_HDR
	LD	DE,RX_BUF
	LD	BC,RX_BUF_SIZE
	CALL	@RTL.READ_PACKET
	JP	C,.LP
	; EtherType IPv4
	LD	A,(RX_BUF + 12)
	CP	HIGH ETH_TYPE_IPV4
	JP	NZ,.LP
	LD	A,(RX_BUF + 13)
	CP	LOW ETH_TYPE_IPV4
	JP	NZ,.LP
	; IP version+IHL = 0x45
	LD	A,(RX_BUF + 14)
	CP	0x45
	JP	NZ,.LP
	; protocol = UDP
	LD	A,(RX_BUF + 14 + 9)
	CP	IP_PROTO_UDP
	JP	NZ,.LP
	; src IP == TARGET_IP
	LD	HL,RX_BUF + 14 + 12
	LD	DE,TARGET_IP
	LD	B,4
.CMPSRC
	LD	A,(DE)
	CP	(HL)
	JP	NZ,.LP
	INC	HL
	INC	DE
	DJNZ	.CMPSRC
	; UDP src_port == TARGET_PORT
	LD	A,(TARGET_PORT_HI)
	LD	C,A
	LD	A,(RX_BUF + 14 + IP_HDR_LEN + 0)
	CP	C
	JP	NZ,.LP
	LD	A,(TARGET_PORT_LO)
	LD	C,A
	LD	A,(RX_BUF + 14 + IP_HDR_LEN + 1)
	CP	C
	JP	NZ,.LP
	; UDP dst_port == OUR_PORT
	LD	A,(RX_BUF + 14 + IP_HDR_LEN + 2)
	CP	OUR_PORT_HI
	JP	NZ,.LP
	LD	A,(RX_BUF + 14 + IP_HDR_LEN + 3)
	CP	OUR_PORT_LO
	JP	NZ,.LP
	; UDP length = bytes 4..5 BE; payload length = UDP_LEN - 8
	LD	A,(RX_BUF + 14 + IP_HDR_LEN + 5)
	LD	L,A
	LD	A,(RX_BUF + 14 + IP_HDR_LEN + 4)
	LD	H,A
	LD	BC,8
	OR	A
	SBC	HL,BC
	; cap at REPLY_BUF_SIZE
	LD	BC,REPLY_BUF_SIZE
	LD	A,H
	CP	B
	JR	C,.LEN_OK
	JR	NZ,.LEN_CAP
	LD	A,L
	CP	C
	JR	C,.LEN_OK
.LEN_CAP
	LD	HL,REPLY_BUF_SIZE
.LEN_OK
	LD	(REPLY_LEN),HL
	; copy payload from RX_BUF + 14 + IP_HDR_LEN + UDP_HDR_LEN
	LD	HL,RX_BUF + 14 + IP_HDR_LEN + UDP_HDR_LEN
	LD	DE,REPLY_BUF
	LD	BC,(REPLY_LEN)
	LD	A,B
	OR	C
	JR	Z,.NOCOPY
	LDIR
.NOCOPY
	OR	A
	RET
.TIMEOUT
	SCF
	RET


; ------------------------------------------------------
; PRINT_TEXT: print BC bytes from (HL) as printable chars,
; substituting '.' for control bytes.
; ------------------------------------------------------
PRINT_TEXT
	PUSH	BC,HL
.LP
	LD	A,B
	OR	C
	JR	Z,.DONE
	LD	A,(HL)
	CP	32
	JR	C,.DOT
	CP	127
	JR	NC,.DOT
	JR	.OUT
.DOT
	LD	A,'.'
.OUT
	PUSH	BC,HL
	LD	C,DSS_PUTCHAR
	RST	DSS
	POP	HL,BC
	INC	HL
	DEC	BC
	JR	.LP
.DONE
	POP	HL,BC
	RET


PRINT_IPV4
	PUSH	HL,BC
	LD	B,4
.LP
	LD	A,(HL)
	CALL	PRINT_DEC_A
	INC	HL
	DEC	B
	JR	Z,.DONE
	PUSH	BC
	LD	A,'.'
	LD	C,DSS_PUTCHAR
	RST	DSS
	POP	BC
	JR	.LP
.DONE
	POP	BC,HL
	RET


PRINT_DEC_A
	PUSH	AF,BC,DE,HL
	LD	C,A
	LD	HL,DEC_BUF + 5
	LD	(HL),0
.LP
	LD	A,C
	LD	B,0
.SUB
	CP	10
	JR	C,.GOT
	SUB	10
	INC	B
	JR	.SUB
.GOT
	ADD	A,'0'
	DEC	HL
	LD	(HL),A
	LD	C,B
	LD	A,B
	OR	A
	JR	NZ,.LP
	LD	C,DSS_PCHARS
	RST	DSS
	POP	HL,DE,BC,AF
	RET

DEC_BUF		EQU APP_BSS_BASE + 20		; 6 bytes scratch for PRINT_DEC_A


PUTCHAR
	PUSH	AF,BC
	LD	C,DSS_PUTCHAR
	RST	DSS
	POP	BC,AF
	RET


PRINT_REG_DUMP
	PRINT MSG_REGS
	LD	HL,REG_NAMES
	LD	DE,@RTL.REG_SNAPSHOT
	LD	B,@RTL.REG_SNAPSHOT_LEN
.LP
	PUSH	BC,DE
.NCHR
	LD	A,(HL)
	INC	HL
	OR	A
	JR	Z,.NDONE
	CALL	PUTCHAR
	JR	.NCHR
.NDONE
	LD	A,'='
	CALL	PUTCHAR
	POP	DE,BC
	LD	A,(DE)
	CALL	@UTIL.PRINT_HEX_A
	LD	A,' '
	CALL	PUTCHAR
	INC	DE
	DJNZ	.LP
	PRINT LINE_END
	RET

REG_NAMES
	DB "CR",0
	DB "ISR",0
	DB "DCR",0
	DB "RCR",0
	DB "TCR",0
	DB "IMR",0
	DB "PSTART",0
	DB "PSTOP",0
	DB "BNRY",0
	DB "CURR",0


; ------- in-EXE data -------
N_NET_IP	DB "NET_IP",0
N_NET_MAC	DB "NET_MAC",0
PAYLOAD		DB "SPRINTER UDPTEST"

; ------- runtime BSS (lives at APP_BSS_BASE, NOT in .EXE) --
OUR_IP		EQU APP_BSS_BASE		; 4 bytes
OUR_MAC		EQU APP_BSS_BASE + 4		; 6 bytes
TARGET_IP	EQU APP_BSS_BASE + 10		; 4 bytes (from positional arg)
TARGET_MAC	EQU APP_BSS_BASE + 14		; 6 bytes
TARGET_PORT_HI	EQU APP_BSS_BASE + 20		; 1 byte (from positional arg)
TARGET_PORT_LO	EQU APP_BSS_BASE + 21		; 1 byte
TIMEOUT_MS_LEFT	EQU APP_BSS_BASE + 22		; 2 bytes
REPLY_LEN	EQU APP_BSS_BASE + 24		; 2 bytes
CANCELLED	EQU APP_BSS_BASE + 26		; 1 byte
TARGET_HOST_PTR	EQU APP_BSS_BASE + 27		; 2 bytes (-> argv token)


; ------- messages -------
MSG_BANNER	DB "RTL8019AS UDPTEST v0.2",0
MSG_SENDING_TO	DB "Sending UDP to ",0
MSG_FROM_HOST	DB " from ",0
MSG_REPLY_LEN	DB "Reply: len=",0
MSG_DATA_EQ	DB " data=",0
MSG_REGS	DB "REGS ",0
MSG_ABORTED	DB "Aborted by user (Esc/Ctrl+C).",0
MSG_E_RESET	DB "[E70] RESET timeout",0
MSG_E_SEND	DB "[E71] DMA write or PTX timeout",0
MSG_E_ARP	DB "ARP request timed out.",0
MSG_E_UDP	DB "UDP reply timed out.",0
MSG_USAGE_ERR	DB "[E] usage: missing or invalid arguments",0
MSG_E_RESOLVE	DB "[E] could not resolve host (DNS / ARP timeout or NXDOMAIN).",0
MSG_E_NO_DNS1	DB "[E] NET_DNS1 not set; pass an IPv4 literal or run NETCFG/IFUP first.",0
MSG_E_NO_GW	DB "[E] DNS server is off-subnet but NET_GW is not set.",0
MSG_HELP
	DB "Usage:",13,10
	DB "  UDPTEST host port",13,10
	DB "  UDPTEST /?",13,10,13,10
	DB "  host  destination IPv4 (e.g. 192.168.7.1).",13,10
	DB "  port  destination UDP port (1..65535).",13,10
	DB "Sends a fixed 16-byte payload (\"SPRINTER UDPTEST\")",13,10
	DB "and waits for an echo reply.  Esc or Ctrl+C aborts.",13,10,0
LINE_END	DB 13,10,0

	ENDMODULE


	; netenv_lib / cmdline_lib transitively DEFINE USE_UTIL_*
	; helpers; include BEFORE util.asm.
	INCLUDE "netenv_lib.asm"
	INCLUDE "cmdline_lib.asm"
	INCLUDE "isa.asm"
	INCLUDE "util.asm"
	INCLUDE "rtl8019.asm"
	INCLUDE "arp_lib.asm"
	INCLUDE "resolve_lib.asm"
	INCLUDE "dns_lib.asm"


UDPTEST_IMAGE_END

RX_BUF_SIZE	EQU 1518
REPLY_BUF_SIZE	EQU 256

	MODULE MAIN

; resolve_lib's DNS query frame may reach RESOLVE_MAX_FRAME (320),
; larger than UDP_FRAME_LEN (58); reserve the bigger of the two.
TX_BUF		EQU UDPTEST_IMAGE_END
RX_HDR		EQU TX_BUF + RESOLVE_MAX_FRAME
RX_BUF		EQU RX_HDR + 4
REPLY_BUF	EQU RX_BUF + RX_BUF_SIZE
UDPTEST_BSS_END	EQU REPLY_BUF + REPLY_BUF_SIZE

	ENDMODULE

	END MAIN.START
